mod archive_adapter;
mod blocking;
pub mod builtins;
mod command_abi;
mod download_client_adapter;
mod embedded_descriptor;
mod indexer_adapter;
mod legacy_runtime;
mod loader;
pub mod newznab_profiles;
mod notification_adapter;
mod plugin_http_host;
mod process_host;
mod runtime_backing;
mod runtime_features;
mod seeding_trust;
mod socket_host;
mod subtitle_adapter;
mod subtitle_sync_adapter;
mod types;
mod wasmtime_host;

pub use loader::DynamicArchiveExtractorPluginProvider;
pub use loader::DynamicDownloadClientPluginProvider;
pub use loader::DynamicNotificationPluginProvider;
pub use loader::DynamicPluginProvider;
pub use loader::DynamicSubtitlePluginProvider;
pub use loader::WasmArchiveExtractorPluginProvider;
pub use loader::WasmDownloadClientPluginProvider;
pub use loader::WasmIndexerPluginProvider;
pub use loader::WasmNotificationPluginProvider;
pub use loader::WasmPluginDescriptorLoader;
pub use loader::WasmSubtitlePluginProvider;
pub use loader::build_archive_extractor_plugin_provider;
pub use loader::build_archive_extractor_plugin_provider_from_runtime_plugins;
pub use loader::build_download_client_plugin_provider;
pub use loader::build_download_client_plugin_provider_from_runtime_plugins;
pub use loader::build_indexer_plugin_provider;
pub use loader::build_indexer_plugin_provider_from_runtime_plugins;
pub use loader::build_notification_plugin_provider;
pub use loader::build_notification_plugin_provider_from_runtime_plugins;
pub use loader::build_subtitle_plugin_provider;
pub use loader::build_subtitle_plugin_provider_from_runtime_plugins;
pub use loader::load_indexer_plugins;
pub use loader::schedule_plugin_rehydration;
pub use plugin_http_host::PluginHttpRuntime;
pub use plugin_http_host::shared_plugin_http_runtime;
pub use runtime_features::PLUGIN_REQUIRED_FEATURE_RELAXED_SIMD;
pub use runtime_features::PLUGIN_REQUIRED_FEATURE_SIMD128;
pub use runtime_features::detect_supported_plugin_required_features;
pub use scryer_plugin_sdk::SDK_VERSION;
pub use scryer_plugin_sdk::host_version_matches_constraint;
pub use scryer_plugin_sdk::sdk_constraint_or_legacy;
pub use scryer_plugin_sdk::validate_sdk_contract;
pub use types::{ConfigFieldDef, ConfigFieldOption};
pub use wasmtime_host::engine::{initialize_wasm_runtime, initialize_wasm_runtime_at};
