[package]
name = "scryer-interface-query"
version = "0.19.5"
edition.workspace = true

[dependencies]
scryer-application = { path = "../scryer-application" }
scryer-domain = { path = "../scryer-domain" }
scryer-interface-core = { path = "../scryer-interface-core" }
scryer-interface-media = { path = "../scryer-interface-media" }
scryer-interface-metadata = { path = "../scryer-interface-metadata" }
scryer-interface-settings = { path = "../scryer-interface-settings" }
async-graphql = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
