#[derive(Clone, Copy, Debug)]
pub(super) struct LanguageLookupEntry {
    pub canonical: &'static str,
    pub bibliographic: &'static str,
    pub two_letter: &'static str,
    pub english_name: &'static str,
}

pub(super) const ISO6392_LANGUAGE_ENTRIES: &[LanguageLookupEntry] = &[
    LanguageLookupEntry {
        canonical: "aar",
        bibliographic: "",
        two_letter: "aa",
        english_name: "Afar",
    },
    LanguageLookupEntry {
        canonical: "abk",
        bibliographic: "",
        two_letter: "ab",
        english_name: "Abkhazian",
    },
    LanguageLookupEntry {
        canonical: "ace",
        bibliographic: "",
        two_letter: "",
        english_name: "Achinese",
    },
    LanguageLookupEntry {
        canonical: "ach",
        bibliographic: "",
        two_letter: "",
        english_name: "Acoli",
    },
    LanguageLookupEntry {
        canonical: "ada",
        bibliographic: "",
        two_letter: "",
        english_name: "Adangme",
    },
    LanguageLookupEntry {
        canonical: "ady",
        bibliographic: "",
        two_letter: "",
        english_name: "Adyghe; Adygei",
    },
    LanguageLookupEntry {
        canonical: "afa",
        bibliographic: "",
        two_letter: "",
        english_name: "Afro-Asiatic languages",
    },
    LanguageLookupEntry {
        canonical: "afh",
        bibliographic: "",
        two_letter: "",
        english_name: "Afrihili",
    },
    LanguageLookupEntry {
        canonical: "afr",
        bibliographic: "",
        two_letter: "af",
        english_name: "Afrikaans",
    },
    LanguageLookupEntry {
        canonical: "ain",
        bibliographic: "",
        two_letter: "",
        english_name: "Ainu",
    },
    LanguageLookupEntry {
        canonical: "aka",
        bibliographic: "",
        two_letter: "ak",
        english_name: "Akan",
    },
    LanguageLookupEntry {
        canonical: "akk",
        bibliographic: "",
        two_letter: "",
        english_name: "Akkadian",
    },
    LanguageLookupEntry {
        canonical: "ale",
        bibliographic: "",
        two_letter: "",
        english_name: "Aleut",
    },
    LanguageLookupEntry {
        canonical: "alg",
        bibliographic: "",
        two_letter: "",
        english_name: "Algonquian languages",
    },
    LanguageLookupEntry {
        canonical: "alt",
        bibliographic: "",
        two_letter: "",
        english_name: "Southern Altai",
    },
    LanguageLookupEntry {
        canonical: "amh",
        bibliographic: "",
        two_letter: "am",
        english_name: "Amharic",
    },
    LanguageLookupEntry {
        canonical: "ang",
        bibliographic: "",
        two_letter: "",
        english_name: "English, Old (ca.450-1100)",
    },
    LanguageLookupEntry {
        canonical: "anp",
        bibliographic: "",
        two_letter: "",
        english_name: "Angika",
    },
    LanguageLookupEntry {
        canonical: "apa",
        bibliographic: "",
        two_letter: "",
        english_name: "Apache languages",
    },
    LanguageLookupEntry {
        canonical: "ara",
        bibliographic: "",
        two_letter: "ar",
        english_name: "Arabic",
    },
    LanguageLookupEntry {
        canonical: "arc",
        bibliographic: "",
        two_letter: "",
        english_name: "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)",
    },
    LanguageLookupEntry {
        canonical: "arg",
        bibliographic: "",
        two_letter: "an",
        english_name: "Aragonese",
    },
    LanguageLookupEntry {
        canonical: "arn",
        bibliographic: "",
        two_letter: "",
        english_name: "Mapudungun; Mapuche",
    },
    LanguageLookupEntry {
        canonical: "arp",
        bibliographic: "",
        two_letter: "",
        english_name: "Arapaho",
    },
    LanguageLookupEntry {
        canonical: "art",
        bibliographic: "",
        two_letter: "",
        english_name: "Artificial languages",
    },
    LanguageLookupEntry {
        canonical: "arw",
        bibliographic: "",
        two_letter: "",
        english_name: "Arawak",
    },
    LanguageLookupEntry {
        canonical: "asm",
        bibliographic: "",
        two_letter: "as",
        english_name: "Assamese",
    },
    LanguageLookupEntry {
        canonical: "ast",
        bibliographic: "",
        two_letter: "",
        english_name: "Asturian; Bable; Leonese; Asturleonese",
    },
    LanguageLookupEntry {
        canonical: "ath",
        bibliographic: "",
        two_letter: "",
        english_name: "Athapascan languages",
    },
    LanguageLookupEntry {
        canonical: "aus",
        bibliographic: "",
        two_letter: "",
        english_name: "Australian languages",
    },
    LanguageLookupEntry {
        canonical: "ava",
        bibliographic: "",
        two_letter: "av",
        english_name: "Avaric",
    },
    LanguageLookupEntry {
        canonical: "ave",
        bibliographic: "",
        two_letter: "ae",
        english_name: "Avestan",
    },
    LanguageLookupEntry {
        canonical: "awa",
        bibliographic: "",
        two_letter: "",
        english_name: "Awadhi",
    },
    LanguageLookupEntry {
        canonical: "aym",
        bibliographic: "",
        two_letter: "ay",
        english_name: "Aymara",
    },
    LanguageLookupEntry {
        canonical: "aze",
        bibliographic: "",
        two_letter: "az",
        english_name: "Azerbaijani",
    },
    LanguageLookupEntry {
        canonical: "bad",
        bibliographic: "",
        two_letter: "",
        english_name: "Banda languages",
    },
    LanguageLookupEntry {
        canonical: "bai",
        bibliographic: "",
        two_letter: "",
        english_name: "Bamileke languages",
    },
    LanguageLookupEntry {
        canonical: "bak",
        bibliographic: "",
        two_letter: "ba",
        english_name: "Bashkir",
    },
    LanguageLookupEntry {
        canonical: "bal",
        bibliographic: "",
        two_letter: "",
        english_name: "Baluchi",
    },
    LanguageLookupEntry {
        canonical: "bam",
        bibliographic: "",
        two_letter: "bm",
        english_name: "Bambara",
    },
    LanguageLookupEntry {
        canonical: "ban",
        bibliographic: "",
        two_letter: "",
        english_name: "Balinese",
    },
    LanguageLookupEntry {
        canonical: "bas",
        bibliographic: "",
        two_letter: "",
        english_name: "Basa",
    },
    LanguageLookupEntry {
        canonical: "bat",
        bibliographic: "",
        two_letter: "",
        english_name: "Baltic languages",
    },
    LanguageLookupEntry {
        canonical: "bej",
        bibliographic: "",
        two_letter: "",
        english_name: "Beja; Bedawiyet",
    },
    LanguageLookupEntry {
        canonical: "bel",
        bibliographic: "",
        two_letter: "be",
        english_name: "Belarusian",
    },
    LanguageLookupEntry {
        canonical: "bem",
        bibliographic: "",
        two_letter: "",
        english_name: "Bemba",
    },
    LanguageLookupEntry {
        canonical: "ben",
        bibliographic: "",
        two_letter: "bn",
        english_name: "Bengali",
    },
    LanguageLookupEntry {
        canonical: "ber",
        bibliographic: "",
        two_letter: "",
        english_name: "Berber languages",
    },
    LanguageLookupEntry {
        canonical: "bho",
        bibliographic: "",
        two_letter: "",
        english_name: "Bhojpuri",
    },
    LanguageLookupEntry {
        canonical: "bih",
        bibliographic: "",
        two_letter: "bh",
        english_name: "Bihari languages",
    },
    LanguageLookupEntry {
        canonical: "bik",
        bibliographic: "",
        two_letter: "",
        english_name: "Bikol",
    },
    LanguageLookupEntry {
        canonical: "bin",
        bibliographic: "",
        two_letter: "",
        english_name: "Bini; Edo",
    },
    LanguageLookupEntry {
        canonical: "bis",
        bibliographic: "",
        two_letter: "bi",
        english_name: "Bislama",
    },
    LanguageLookupEntry {
        canonical: "bla",
        bibliographic: "",
        two_letter: "",
        english_name: "Siksika",
    },
    LanguageLookupEntry {
        canonical: "bnt",
        bibliographic: "",
        two_letter: "",
        english_name: "Bantu (Other)",
    },
    LanguageLookupEntry {
        canonical: "bod",
        bibliographic: "tib",
        two_letter: "bo",
        english_name: "Tibetan",
    },
    LanguageLookupEntry {
        canonical: "bos",
        bibliographic: "",
        two_letter: "bs",
        english_name: "Bosnian",
    },
    LanguageLookupEntry {
        canonical: "bra",
        bibliographic: "",
        two_letter: "",
        english_name: "Braj",
    },
    LanguageLookupEntry {
        canonical: "bre",
        bibliographic: "",
        two_letter: "br",
        english_name: "Breton",
    },
    LanguageLookupEntry {
        canonical: "btk",
        bibliographic: "",
        two_letter: "",
        english_name: "Batak languages",
    },
    LanguageLookupEntry {
        canonical: "bua",
        bibliographic: "",
        two_letter: "",
        english_name: "Buriat",
    },
    LanguageLookupEntry {
        canonical: "bug",
        bibliographic: "",
        two_letter: "",
        english_name: "Buginese",
    },
    LanguageLookupEntry {
        canonical: "bul",
        bibliographic: "",
        two_letter: "bg",
        english_name: "Bulgarian",
    },
    LanguageLookupEntry {
        canonical: "byn",
        bibliographic: "",
        two_letter: "",
        english_name: "Blin; Bilin",
    },
    LanguageLookupEntry {
        canonical: "cad",
        bibliographic: "",
        two_letter: "",
        english_name: "Caddo",
    },
    LanguageLookupEntry {
        canonical: "cai",
        bibliographic: "",
        two_letter: "",
        english_name: "Central American Indian languages",
    },
    LanguageLookupEntry {
        canonical: "car",
        bibliographic: "",
        two_letter: "",
        english_name: "Galibi Carib",
    },
    LanguageLookupEntry {
        canonical: "cat",
        bibliographic: "",
        two_letter: "ca",
        english_name: "Catalan; Valencian",
    },
    LanguageLookupEntry {
        canonical: "cau",
        bibliographic: "",
        two_letter: "",
        english_name: "Caucasian languages",
    },
    LanguageLookupEntry {
        canonical: "ceb",
        bibliographic: "",
        two_letter: "",
        english_name: "Cebuano",
    },
    LanguageLookupEntry {
        canonical: "cel",
        bibliographic: "",
        two_letter: "",
        english_name: "Celtic languages",
    },
    LanguageLookupEntry {
        canonical: "ces",
        bibliographic: "cze",
        two_letter: "cs",
        english_name: "Czech",
    },
    LanguageLookupEntry {
        canonical: "cha",
        bibliographic: "",
        two_letter: "ch",
        english_name: "Chamorro",
    },
    LanguageLookupEntry {
        canonical: "chb",
        bibliographic: "",
        two_letter: "",
        english_name: "Chibcha",
    },
    LanguageLookupEntry {
        canonical: "che",
        bibliographic: "",
        two_letter: "ce",
        english_name: "Chechen",
    },
    LanguageLookupEntry {
        canonical: "chg",
        bibliographic: "",
        two_letter: "",
        english_name: "Chagatai",
    },
    LanguageLookupEntry {
        canonical: "chk",
        bibliographic: "",
        two_letter: "",
        english_name: "Chuukese",
    },
    LanguageLookupEntry {
        canonical: "chm",
        bibliographic: "",
        two_letter: "",
        english_name: "Mari",
    },
    LanguageLookupEntry {
        canonical: "chn",
        bibliographic: "",
        two_letter: "",
        english_name: "Chinook jargon",
    },
    LanguageLookupEntry {
        canonical: "cho",
        bibliographic: "",
        two_letter: "",
        english_name: "Choctaw",
    },
    LanguageLookupEntry {
        canonical: "chp",
        bibliographic: "",
        two_letter: "",
        english_name: "Chipewyan; Dene Suline",
    },
    LanguageLookupEntry {
        canonical: "chr",
        bibliographic: "",
        two_letter: "",
        english_name: "Cherokee",
    },
    LanguageLookupEntry {
        canonical: "chu",
        bibliographic: "",
        two_letter: "cu",
        english_name: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
    },
    LanguageLookupEntry {
        canonical: "chv",
        bibliographic: "",
        two_letter: "cv",
        english_name: "Chuvash",
    },
    LanguageLookupEntry {
        canonical: "chy",
        bibliographic: "",
        two_letter: "",
        english_name: "Cheyenne",
    },
    LanguageLookupEntry {
        canonical: "cmc",
        bibliographic: "",
        two_letter: "",
        english_name: "Chamic languages",
    },
    LanguageLookupEntry {
        canonical: "cop",
        bibliographic: "",
        two_letter: "",
        english_name: "Coptic",
    },
    LanguageLookupEntry {
        canonical: "cor",
        bibliographic: "",
        two_letter: "kw",
        english_name: "Cornish",
    },
    LanguageLookupEntry {
        canonical: "cos",
        bibliographic: "",
        two_letter: "co",
        english_name: "Corsican",
    },
    LanguageLookupEntry {
        canonical: "cpe",
        bibliographic: "",
        two_letter: "",
        english_name: "Creoles and pidgins, English based",
    },
    LanguageLookupEntry {
        canonical: "cpf",
        bibliographic: "",
        two_letter: "",
        english_name: "Creoles and pidgins, French-based ",
    },
    LanguageLookupEntry {
        canonical: "cpp",
        bibliographic: "",
        two_letter: "",
        english_name: "Creoles and pidgins, Portuguese-based ",
    },
    LanguageLookupEntry {
        canonical: "cre",
        bibliographic: "",
        two_letter: "cr",
        english_name: "Cree",
    },
    LanguageLookupEntry {
        canonical: "crh",
        bibliographic: "",
        two_letter: "",
        english_name: "Crimean Tatar; Crimean Turkish",
    },
    LanguageLookupEntry {
        canonical: "crp",
        bibliographic: "",
        two_letter: "",
        english_name: "Creoles and pidgins ",
    },
    LanguageLookupEntry {
        canonical: "csb",
        bibliographic: "",
        two_letter: "",
        english_name: "Kashubian",
    },
    LanguageLookupEntry {
        canonical: "cus",
        bibliographic: "",
        two_letter: "",
        english_name: "Cushitic languages",
    },
    LanguageLookupEntry {
        canonical: "cym",
        bibliographic: "wel",
        two_letter: "cy",
        english_name: "Welsh",
    },
    LanguageLookupEntry {
        canonical: "dak",
        bibliographic: "",
        two_letter: "",
        english_name: "Dakota",
    },
    LanguageLookupEntry {
        canonical: "dan",
        bibliographic: "",
        two_letter: "da",
        english_name: "Danish",
    },
    LanguageLookupEntry {
        canonical: "dar",
        bibliographic: "",
        two_letter: "",
        english_name: "Dargwa",
    },
    LanguageLookupEntry {
        canonical: "day",
        bibliographic: "",
        two_letter: "",
        english_name: "Land Dayak languages",
    },
    LanguageLookupEntry {
        canonical: "del",
        bibliographic: "",
        two_letter: "",
        english_name: "Delaware",
    },
    LanguageLookupEntry {
        canonical: "den",
        bibliographic: "",
        two_letter: "",
        english_name: "Slave (Athapascan)",
    },
    LanguageLookupEntry {
        canonical: "deu",
        bibliographic: "ger",
        two_letter: "de",
        english_name: "German",
    },
    LanguageLookupEntry {
        canonical: "dgr",
        bibliographic: "",
        two_letter: "",
        english_name: "Dogrib",
    },
    LanguageLookupEntry {
        canonical: "din",
        bibliographic: "",
        two_letter: "",
        english_name: "Dinka",
    },
    LanguageLookupEntry {
        canonical: "div",
        bibliographic: "",
        two_letter: "dv",
        english_name: "Divehi; Dhivehi; Maldivian",
    },
    LanguageLookupEntry {
        canonical: "doi",
        bibliographic: "",
        two_letter: "",
        english_name: "Dogri",
    },
    LanguageLookupEntry {
        canonical: "dra",
        bibliographic: "",
        two_letter: "",
        english_name: "Dravidian languages",
    },
    LanguageLookupEntry {
        canonical: "dsb",
        bibliographic: "",
        two_letter: "",
        english_name: "Lower Sorbian",
    },
    LanguageLookupEntry {
        canonical: "dua",
        bibliographic: "",
        two_letter: "",
        english_name: "Duala",
    },
    LanguageLookupEntry {
        canonical: "dum",
        bibliographic: "",
        two_letter: "",
        english_name: "Dutch, Middle (ca.1050-1350)",
    },
    LanguageLookupEntry {
        canonical: "dyu",
        bibliographic: "",
        two_letter: "",
        english_name: "Dyula",
    },
    LanguageLookupEntry {
        canonical: "dzo",
        bibliographic: "",
        two_letter: "dz",
        english_name: "Dzongkha",
    },
    LanguageLookupEntry {
        canonical: "efi",
        bibliographic: "",
        two_letter: "",
        english_name: "Efik",
    },
    LanguageLookupEntry {
        canonical: "egy",
        bibliographic: "",
        two_letter: "",
        english_name: "Egyptian (Ancient)",
    },
    LanguageLookupEntry {
        canonical: "eka",
        bibliographic: "",
        two_letter: "",
        english_name: "Ekajuk",
    },
    LanguageLookupEntry {
        canonical: "ell",
        bibliographic: "gre",
        two_letter: "el",
        english_name: "Greek, Modern (1453-)",
    },
    LanguageLookupEntry {
        canonical: "elx",
        bibliographic: "",
        two_letter: "",
        english_name: "Elamite",
    },
    LanguageLookupEntry {
        canonical: "eng",
        bibliographic: "",
        two_letter: "en",
        english_name: "English",
    },
    LanguageLookupEntry {
        canonical: "enm",
        bibliographic: "",
        two_letter: "",
        english_name: "English, Middle (1100-1500)",
    },
    LanguageLookupEntry {
        canonical: "epo",
        bibliographic: "",
        two_letter: "eo",
        english_name: "Esperanto",
    },
    LanguageLookupEntry {
        canonical: "est",
        bibliographic: "",
        two_letter: "et",
        english_name: "Estonian",
    },
    LanguageLookupEntry {
        canonical: "eus",
        bibliographic: "baq",
        two_letter: "eu",
        english_name: "Basque",
    },
    LanguageLookupEntry {
        canonical: "ewe",
        bibliographic: "",
        two_letter: "ee",
        english_name: "Ewe",
    },
    LanguageLookupEntry {
        canonical: "ewo",
        bibliographic: "",
        two_letter: "",
        english_name: "Ewondo",
    },
    LanguageLookupEntry {
        canonical: "fan",
        bibliographic: "",
        two_letter: "",
        english_name: "Fang",
    },
    LanguageLookupEntry {
        canonical: "fao",
        bibliographic: "",
        two_letter: "fo",
        english_name: "Faroese",
    },
    LanguageLookupEntry {
        canonical: "fas",
        bibliographic: "per",
        two_letter: "fa",
        english_name: "Persian",
    },
    LanguageLookupEntry {
        canonical: "fat",
        bibliographic: "",
        two_letter: "",
        english_name: "Fanti",
    },
    LanguageLookupEntry {
        canonical: "fij",
        bibliographic: "",
        two_letter: "fj",
        english_name: "Fijian",
    },
    LanguageLookupEntry {
        canonical: "fil",
        bibliographic: "",
        two_letter: "",
        english_name: "Filipino; Pilipino",
    },
    LanguageLookupEntry {
        canonical: "fin",
        bibliographic: "",
        two_letter: "fi",
        english_name: "Finnish",
    },
    LanguageLookupEntry {
        canonical: "fiu",
        bibliographic: "",
        two_letter: "",
        english_name: "Finno-Ugrian languages",
    },
    LanguageLookupEntry {
        canonical: "fon",
        bibliographic: "",
        two_letter: "",
        english_name: "Fon",
    },
    LanguageLookupEntry {
        canonical: "fra",
        bibliographic: "fre",
        two_letter: "fr",
        english_name: "French",
    },
    LanguageLookupEntry {
        canonical: "frm",
        bibliographic: "",
        two_letter: "",
        english_name: "French, Middle (ca.1400-1600)",
    },
    LanguageLookupEntry {
        canonical: "fro",
        bibliographic: "",
        two_letter: "",
        english_name: "French, Old (842-ca.1400)",
    },
    LanguageLookupEntry {
        canonical: "frc",
        bibliographic: "",
        two_letter: "fr-ca",
        english_name: "French (Canada)",
    },
    LanguageLookupEntry {
        canonical: "frr",
        bibliographic: "",
        two_letter: "",
        english_name: "Northern Frisian",
    },
    LanguageLookupEntry {
        canonical: "frs",
        bibliographic: "",
        two_letter: "",
        english_name: "Eastern Frisian",
    },
    LanguageLookupEntry {
        canonical: "fry",
        bibliographic: "",
        two_letter: "fy",
        english_name: "Western Frisian",
    },
    LanguageLookupEntry {
        canonical: "ful",
        bibliographic: "",
        two_letter: "ff",
        english_name: "Fulah",
    },
    LanguageLookupEntry {
        canonical: "fur",
        bibliographic: "",
        two_letter: "",
        english_name: "Friulian",
    },
    LanguageLookupEntry {
        canonical: "gaa",
        bibliographic: "",
        two_letter: "",
        english_name: "Ga",
    },
    LanguageLookupEntry {
        canonical: "gay",
        bibliographic: "",
        two_letter: "",
        english_name: "Gayo",
    },
    LanguageLookupEntry {
        canonical: "gba",
        bibliographic: "",
        two_letter: "",
        english_name: "Gbaya",
    },
    LanguageLookupEntry {
        canonical: "gem",
        bibliographic: "",
        two_letter: "",
        english_name: "Germanic languages",
    },
    LanguageLookupEntry {
        canonical: "gez",
        bibliographic: "",
        two_letter: "",
        english_name: "Geez",
    },
    LanguageLookupEntry {
        canonical: "gil",
        bibliographic: "",
        two_letter: "",
        english_name: "Gilbertese",
    },
    LanguageLookupEntry {
        canonical: "gla",
        bibliographic: "",
        two_letter: "gd",
        english_name: "Gaelic; Scottish Gaelic",
    },
    LanguageLookupEntry {
        canonical: "gle",
        bibliographic: "",
        two_letter: "ga",
        english_name: "Irish",
    },
    LanguageLookupEntry {
        canonical: "glg",
        bibliographic: "",
        two_letter: "gl",
        english_name: "Galician",
    },
    LanguageLookupEntry {
        canonical: "glv",
        bibliographic: "",
        two_letter: "gv",
        english_name: "Manx",
    },
    LanguageLookupEntry {
        canonical: "gmh",
        bibliographic: "",
        two_letter: "",
        english_name: "German, Middle High (ca.1050-1500)",
    },
    LanguageLookupEntry {
        canonical: "goh",
        bibliographic: "",
        two_letter: "",
        english_name: "German, Old High (ca.750-1050)",
    },
    LanguageLookupEntry {
        canonical: "gon",
        bibliographic: "",
        two_letter: "",
        english_name: "Gondi",
    },
    LanguageLookupEntry {
        canonical: "gor",
        bibliographic: "",
        two_letter: "",
        english_name: "Gorontalo",
    },
    LanguageLookupEntry {
        canonical: "got",
        bibliographic: "",
        two_letter: "",
        english_name: "Gothic",
    },
    LanguageLookupEntry {
        canonical: "grb",
        bibliographic: "",
        two_letter: "",
        english_name: "Grebo",
    },
    LanguageLookupEntry {
        canonical: "grc",
        bibliographic: "",
        two_letter: "",
        english_name: "Greek, Ancient (to 1453)",
    },
    LanguageLookupEntry {
        canonical: "grn",
        bibliographic: "",
        two_letter: "gn",
        english_name: "Guarani",
    },
    LanguageLookupEntry {
        canonical: "gsw",
        bibliographic: "",
        two_letter: "",
        english_name: "Swiss German; Alemannic; Alsatian",
    },
    LanguageLookupEntry {
        canonical: "guj",
        bibliographic: "",
        two_letter: "gu",
        english_name: "Gujarati",
    },
    LanguageLookupEntry {
        canonical: "gwi",
        bibliographic: "",
        two_letter: "",
        english_name: "Gwich'in",
    },
    LanguageLookupEntry {
        canonical: "hai",
        bibliographic: "",
        two_letter: "",
        english_name: "Haida",
    },
    LanguageLookupEntry {
        canonical: "hat",
        bibliographic: "",
        two_letter: "ht",
        english_name: "Haitian; Haitian Creole",
    },
    LanguageLookupEntry {
        canonical: "hau",
        bibliographic: "",
        two_letter: "ha",
        english_name: "Hausa",
    },
    LanguageLookupEntry {
        canonical: "haw",
        bibliographic: "",
        two_letter: "",
        english_name: "Hawaiian",
    },
    LanguageLookupEntry {
        canonical: "heb",
        bibliographic: "",
        two_letter: "he",
        english_name: "Hebrew",
    },
    LanguageLookupEntry {
        canonical: "her",
        bibliographic: "",
        two_letter: "hz",
        english_name: "Herero",
    },
    LanguageLookupEntry {
        canonical: "hil",
        bibliographic: "",
        two_letter: "",
        english_name: "Hiligaynon",
    },
    LanguageLookupEntry {
        canonical: "him",
        bibliographic: "",
        two_letter: "",
        english_name: "Himachali languages; Western Pahari languages",
    },
    LanguageLookupEntry {
        canonical: "hin",
        bibliographic: "",
        two_letter: "hi",
        english_name: "Hindi",
    },
    LanguageLookupEntry {
        canonical: "hit",
        bibliographic: "",
        two_letter: "",
        english_name: "Hittite",
    },
    LanguageLookupEntry {
        canonical: "hmn",
        bibliographic: "",
        two_letter: "",
        english_name: "Hmong; Mong",
    },
    LanguageLookupEntry {
        canonical: "hmo",
        bibliographic: "",
        two_letter: "ho",
        english_name: "Hiri Motu",
    },
    LanguageLookupEntry {
        canonical: "hrv",
        bibliographic: "",
        two_letter: "hr",
        english_name: "Croatian",
    },
    LanguageLookupEntry {
        canonical: "hsb",
        bibliographic: "",
        two_letter: "",
        english_name: "Upper Sorbian",
    },
    LanguageLookupEntry {
        canonical: "hun",
        bibliographic: "",
        two_letter: "hu",
        english_name: "Hungarian",
    },
    LanguageLookupEntry {
        canonical: "hup",
        bibliographic: "",
        two_letter: "",
        english_name: "Hupa",
    },
    LanguageLookupEntry {
        canonical: "hye",
        bibliographic: "arm",
        two_letter: "hy",
        english_name: "Armenian",
    },
    LanguageLookupEntry {
        canonical: "iba",
        bibliographic: "",
        two_letter: "",
        english_name: "Iban",
    },
    LanguageLookupEntry {
        canonical: "ibo",
        bibliographic: "",
        two_letter: "ig",
        english_name: "Igbo",
    },
    LanguageLookupEntry {
        canonical: "isl",
        bibliographic: "ice",
        two_letter: "is",
        english_name: "Icelandic",
    },
    LanguageLookupEntry {
        canonical: "ido",
        bibliographic: "",
        two_letter: "io",
        english_name: "Ido",
    },
    LanguageLookupEntry {
        canonical: "iii",
        bibliographic: "",
        two_letter: "ii",
        english_name: "Sichuan Yi; Nuosu",
    },
    LanguageLookupEntry {
        canonical: "ijo",
        bibliographic: "",
        two_letter: "",
        english_name: "Ijo languages",
    },
    LanguageLookupEntry {
        canonical: "iku",
        bibliographic: "",
        two_letter: "iu",
        english_name: "Inuktitut",
    },
    LanguageLookupEntry {
        canonical: "ile",
        bibliographic: "",
        two_letter: "ie",
        english_name: "Interlingue; Occidental",
    },
    LanguageLookupEntry {
        canonical: "ilo",
        bibliographic: "",
        two_letter: "",
        english_name: "Iloko",
    },
    LanguageLookupEntry {
        canonical: "ina",
        bibliographic: "",
        two_letter: "ia",
        english_name: "Interlingua (International Auxiliary Language Association)",
    },
    LanguageLookupEntry {
        canonical: "inc",
        bibliographic: "",
        two_letter: "",
        english_name: "Indic languages",
    },
    LanguageLookupEntry {
        canonical: "ind",
        bibliographic: "",
        two_letter: "id",
        english_name: "Indonesian",
    },
    LanguageLookupEntry {
        canonical: "ine",
        bibliographic: "",
        two_letter: "",
        english_name: "Indo-European languages",
    },
    LanguageLookupEntry {
        canonical: "inh",
        bibliographic: "",
        two_letter: "",
        english_name: "Ingush",
    },
    LanguageLookupEntry {
        canonical: "ipk",
        bibliographic: "",
        two_letter: "ik",
        english_name: "Inupiaq",
    },
    LanguageLookupEntry {
        canonical: "ira",
        bibliographic: "",
        two_letter: "",
        english_name: "Iranian languages",
    },
    LanguageLookupEntry {
        canonical: "iro",
        bibliographic: "",
        two_letter: "",
        english_name: "Iroquoian languages",
    },
    LanguageLookupEntry {
        canonical: "ita",
        bibliographic: "",
        two_letter: "it",
        english_name: "Italian",
    },
    LanguageLookupEntry {
        canonical: "jav",
        bibliographic: "",
        two_letter: "jv",
        english_name: "Javanese",
    },
    LanguageLookupEntry {
        canonical: "jbo",
        bibliographic: "",
        two_letter: "",
        english_name: "Lojban",
    },
    LanguageLookupEntry {
        canonical: "jpn",
        bibliographic: "",
        two_letter: "ja",
        english_name: "Japanese",
    },
    LanguageLookupEntry {
        canonical: "jpr",
        bibliographic: "",
        two_letter: "",
        english_name: "Judeo-Persian",
    },
    LanguageLookupEntry {
        canonical: "jrb",
        bibliographic: "",
        two_letter: "",
        english_name: "Judeo-Arabic",
    },
    LanguageLookupEntry {
        canonical: "kaa",
        bibliographic: "",
        two_letter: "",
        english_name: "Kara-Kalpak",
    },
    LanguageLookupEntry {
        canonical: "kab",
        bibliographic: "",
        two_letter: "",
        english_name: "Kabyle",
    },
    LanguageLookupEntry {
        canonical: "kac",
        bibliographic: "",
        two_letter: "",
        english_name: "Kachin; Jingpho",
    },
    LanguageLookupEntry {
        canonical: "kal",
        bibliographic: "",
        two_letter: "kl",
        english_name: "Kalaallisut; Greenlandic",
    },
    LanguageLookupEntry {
        canonical: "kam",
        bibliographic: "",
        two_letter: "",
        english_name: "Kamba",
    },
    LanguageLookupEntry {
        canonical: "kan",
        bibliographic: "",
        two_letter: "kn",
        english_name: "Kannada",
    },
    LanguageLookupEntry {
        canonical: "kar",
        bibliographic: "",
        two_letter: "",
        english_name: "Karen languages",
    },
    LanguageLookupEntry {
        canonical: "kas",
        bibliographic: "",
        two_letter: "ks",
        english_name: "Kashmiri",
    },
    LanguageLookupEntry {
        canonical: "kat",
        bibliographic: "geo",
        two_letter: "ka",
        english_name: "Georgian",
    },
    LanguageLookupEntry {
        canonical: "kau",
        bibliographic: "",
        two_letter: "kr",
        english_name: "Kanuri",
    },
    LanguageLookupEntry {
        canonical: "kaw",
        bibliographic: "",
        two_letter: "",
        english_name: "Kawi",
    },
    LanguageLookupEntry {
        canonical: "kaz",
        bibliographic: "",
        two_letter: "kk",
        english_name: "Kazakh",
    },
    LanguageLookupEntry {
        canonical: "kbd",
        bibliographic: "",
        two_letter: "",
        english_name: "Kabardian",
    },
    LanguageLookupEntry {
        canonical: "kha",
        bibliographic: "",
        two_letter: "",
        english_name: "Khasi",
    },
    LanguageLookupEntry {
        canonical: "khi",
        bibliographic: "",
        two_letter: "",
        english_name: "Khoisan languages",
    },
    LanguageLookupEntry {
        canonical: "khm",
        bibliographic: "",
        two_letter: "km",
        english_name: "Central Khmer",
    },
    LanguageLookupEntry {
        canonical: "kho",
        bibliographic: "",
        two_letter: "",
        english_name: "Khotanese; Sakan",
    },
    LanguageLookupEntry {
        canonical: "kik",
        bibliographic: "",
        two_letter: "ki",
        english_name: "Kikuyu; Gikuyu",
    },
    LanguageLookupEntry {
        canonical: "kin",
        bibliographic: "",
        two_letter: "rw",
        english_name: "Kinyarwanda",
    },
    LanguageLookupEntry {
        canonical: "kir",
        bibliographic: "",
        two_letter: "ky",
        english_name: "Kirghiz; Kyrgyz",
    },
    LanguageLookupEntry {
        canonical: "kmb",
        bibliographic: "",
        two_letter: "",
        english_name: "Kimbundu",
    },
    LanguageLookupEntry {
        canonical: "kok",
        bibliographic: "",
        two_letter: "",
        english_name: "Konkani",
    },
    LanguageLookupEntry {
        canonical: "kom",
        bibliographic: "",
        two_letter: "kv",
        english_name: "Komi",
    },
    LanguageLookupEntry {
        canonical: "kon",
        bibliographic: "",
        two_letter: "kg",
        english_name: "Kongo",
    },
    LanguageLookupEntry {
        canonical: "kor",
        bibliographic: "",
        two_letter: "ko",
        english_name: "Korean",
    },
    LanguageLookupEntry {
        canonical: "kos",
        bibliographic: "",
        two_letter: "",
        english_name: "Kosraean",
    },
    LanguageLookupEntry {
        canonical: "kpe",
        bibliographic: "",
        two_letter: "",
        english_name: "Kpelle",
    },
    LanguageLookupEntry {
        canonical: "krc",
        bibliographic: "",
        two_letter: "",
        english_name: "Karachay-Balkar",
    },
    LanguageLookupEntry {
        canonical: "krl",
        bibliographic: "",
        two_letter: "",
        english_name: "Karelian",
    },
    LanguageLookupEntry {
        canonical: "kro",
        bibliographic: "",
        two_letter: "",
        english_name: "Kru languages",
    },
    LanguageLookupEntry {
        canonical: "kru",
        bibliographic: "",
        two_letter: "",
        english_name: "Kurukh",
    },
    LanguageLookupEntry {
        canonical: "kua",
        bibliographic: "",
        two_letter: "kj",
        english_name: "Kuanyama; Kwanyama",
    },
    LanguageLookupEntry {
        canonical: "kum",
        bibliographic: "",
        two_letter: "",
        english_name: "Kumyk",
    },
    LanguageLookupEntry {
        canonical: "kur",
        bibliographic: "",
        two_letter: "ku",
        english_name: "Kurdish",
    },
    LanguageLookupEntry {
        canonical: "kut",
        bibliographic: "",
        two_letter: "",
        english_name: "Kutenai",
    },
    LanguageLookupEntry {
        canonical: "lad",
        bibliographic: "",
        two_letter: "",
        english_name: "Ladino",
    },
    LanguageLookupEntry {
        canonical: "lah",
        bibliographic: "",
        two_letter: "",
        english_name: "Lahnda",
    },
    LanguageLookupEntry {
        canonical: "lam",
        bibliographic: "",
        two_letter: "",
        english_name: "Lamba",
    },
    LanguageLookupEntry {
        canonical: "lao",
        bibliographic: "",
        two_letter: "lo",
        english_name: "Lao",
    },
    LanguageLookupEntry {
        canonical: "lat",
        bibliographic: "",
        two_letter: "la",
        english_name: "Latin",
    },
    LanguageLookupEntry {
        canonical: "lav",
        bibliographic: "",
        two_letter: "lv",
        english_name: "Latvian",
    },
    LanguageLookupEntry {
        canonical: "lez",
        bibliographic: "",
        two_letter: "",
        english_name: "Lezghian",
    },
    LanguageLookupEntry {
        canonical: "lim",
        bibliographic: "",
        two_letter: "li",
        english_name: "Limburgan; Limburger; Limburgish",
    },
    LanguageLookupEntry {
        canonical: "lin",
        bibliographic: "",
        two_letter: "ln",
        english_name: "Lingala",
    },
    LanguageLookupEntry {
        canonical: "lit",
        bibliographic: "",
        two_letter: "lt",
        english_name: "Lithuanian",
    },
    LanguageLookupEntry {
        canonical: "lol",
        bibliographic: "",
        two_letter: "",
        english_name: "Mongo",
    },
    LanguageLookupEntry {
        canonical: "loz",
        bibliographic: "",
        two_letter: "",
        english_name: "Lozi",
    },
    LanguageLookupEntry {
        canonical: "ltz",
        bibliographic: "",
        two_letter: "lb",
        english_name: "Luxembourgish; Letzeburgesch",
    },
    LanguageLookupEntry {
        canonical: "lua",
        bibliographic: "",
        two_letter: "",
        english_name: "Luba-Lulua",
    },
    LanguageLookupEntry {
        canonical: "lub",
        bibliographic: "",
        two_letter: "lu",
        english_name: "Luba-Katanga",
    },
    LanguageLookupEntry {
        canonical: "lug",
        bibliographic: "",
        two_letter: "lg",
        english_name: "Ganda",
    },
    LanguageLookupEntry {
        canonical: "lui",
        bibliographic: "",
        two_letter: "",
        english_name: "Luiseno",
    },
    LanguageLookupEntry {
        canonical: "lun",
        bibliographic: "",
        two_letter: "",
        english_name: "Lunda",
    },
    LanguageLookupEntry {
        canonical: "luo",
        bibliographic: "",
        two_letter: "",
        english_name: "Luo (Kenya and Tanzania)",
    },
    LanguageLookupEntry {
        canonical: "lus",
        bibliographic: "",
        two_letter: "",
        english_name: "Lushai",
    },
    LanguageLookupEntry {
        canonical: "mad",
        bibliographic: "",
        two_letter: "",
        english_name: "Madurese",
    },
    LanguageLookupEntry {
        canonical: "mag",
        bibliographic: "",
        two_letter: "",
        english_name: "Magahi",
    },
    LanguageLookupEntry {
        canonical: "mah",
        bibliographic: "",
        two_letter: "mh",
        english_name: "Marshallese",
    },
    LanguageLookupEntry {
        canonical: "mai",
        bibliographic: "",
        two_letter: "",
        english_name: "Maithili",
    },
    LanguageLookupEntry {
        canonical: "mak",
        bibliographic: "",
        two_letter: "",
        english_name: "Makasar",
    },
    LanguageLookupEntry {
        canonical: "mal",
        bibliographic: "",
        two_letter: "ml",
        english_name: "Malayalam",
    },
    LanguageLookupEntry {
        canonical: "man",
        bibliographic: "",
        two_letter: "",
        english_name: "Mandingo",
    },
    LanguageLookupEntry {
        canonical: "map",
        bibliographic: "",
        two_letter: "",
        english_name: "Austronesian languages",
    },
    LanguageLookupEntry {
        canonical: "mar",
        bibliographic: "",
        two_letter: "mr",
        english_name: "Marathi",
    },
    LanguageLookupEntry {
        canonical: "mas",
        bibliographic: "",
        two_letter: "",
        english_name: "Masai",
    },
    LanguageLookupEntry {
        canonical: "mdf",
        bibliographic: "",
        two_letter: "",
        english_name: "Moksha",
    },
    LanguageLookupEntry {
        canonical: "mdr",
        bibliographic: "",
        two_letter: "",
        english_name: "Mandar",
    },
    LanguageLookupEntry {
        canonical: "men",
        bibliographic: "",
        two_letter: "",
        english_name: "Mende",
    },
    LanguageLookupEntry {
        canonical: "mga",
        bibliographic: "",
        two_letter: "",
        english_name: "Irish, Middle (900-1200)",
    },
    LanguageLookupEntry {
        canonical: "mic",
        bibliographic: "",
        two_letter: "",
        english_name: "Mi'kmaq; Micmac",
    },
    LanguageLookupEntry {
        canonical: "min",
        bibliographic: "",
        two_letter: "",
        english_name: "Minangkabau",
    },
    LanguageLookupEntry {
        canonical: "mis",
        bibliographic: "",
        two_letter: "",
        english_name: "Uncoded languages",
    },
    LanguageLookupEntry {
        canonical: "mkd",
        bibliographic: "mac",
        two_letter: "mk",
        english_name: "Macedonian",
    },
    LanguageLookupEntry {
        canonical: "mkh",
        bibliographic: "",
        two_letter: "",
        english_name: "Mon-Khmer languages",
    },
    LanguageLookupEntry {
        canonical: "mlg",
        bibliographic: "",
        two_letter: "mg",
        english_name: "Malagasy",
    },
    LanguageLookupEntry {
        canonical: "mlt",
        bibliographic: "",
        two_letter: "mt",
        english_name: "Maltese",
    },
    LanguageLookupEntry {
        canonical: "mnc",
        bibliographic: "",
        two_letter: "",
        english_name: "Manchu",
    },
    LanguageLookupEntry {
        canonical: "mni",
        bibliographic: "",
        two_letter: "",
        english_name: "Manipuri",
    },
    LanguageLookupEntry {
        canonical: "mno",
        bibliographic: "",
        two_letter: "",
        english_name: "Manobo languages",
    },
    LanguageLookupEntry {
        canonical: "moh",
        bibliographic: "",
        two_letter: "",
        english_name: "Mohawk",
    },
    LanguageLookupEntry {
        canonical: "mon",
        bibliographic: "",
        two_letter: "mn",
        english_name: "Mongolian",
    },
    LanguageLookupEntry {
        canonical: "mos",
        bibliographic: "",
        two_letter: "",
        english_name: "Mossi",
    },
    LanguageLookupEntry {
        canonical: "mri",
        bibliographic: "mao",
        two_letter: "mi",
        english_name: "Maori",
    },
    LanguageLookupEntry {
        canonical: "msa",
        bibliographic: "may",
        two_letter: "ms",
        english_name: "Malay",
    },
    LanguageLookupEntry {
        canonical: "mul",
        bibliographic: "",
        two_letter: "",
        english_name: "Multiple languages",
    },
    LanguageLookupEntry {
        canonical: "mun",
        bibliographic: "",
        two_letter: "",
        english_name: "Munda languages",
    },
    LanguageLookupEntry {
        canonical: "mus",
        bibliographic: "",
        two_letter: "",
        english_name: "Creek",
    },
    LanguageLookupEntry {
        canonical: "mwl",
        bibliographic: "",
        two_letter: "",
        english_name: "Mirandese",
    },
    LanguageLookupEntry {
        canonical: "mwr",
        bibliographic: "",
        two_letter: "",
        english_name: "Marwari",
    },
    LanguageLookupEntry {
        canonical: "mya",
        bibliographic: "bur",
        two_letter: "my",
        english_name: "Burmese",
    },
    LanguageLookupEntry {
        canonical: "myn",
        bibliographic: "",
        two_letter: "",
        english_name: "Mayan languages",
    },
    LanguageLookupEntry {
        canonical: "myv",
        bibliographic: "",
        two_letter: "",
        english_name: "Erzya",
    },
    LanguageLookupEntry {
        canonical: "nah",
        bibliographic: "",
        two_letter: "",
        english_name: "Nahuatl languages",
    },
    LanguageLookupEntry {
        canonical: "nai",
        bibliographic: "",
        two_letter: "",
        english_name: "North American Indian languages",
    },
    LanguageLookupEntry {
        canonical: "nap",
        bibliographic: "",
        two_letter: "",
        english_name: "Neapolitan",
    },
    LanguageLookupEntry {
        canonical: "nau",
        bibliographic: "",
        two_letter: "na",
        english_name: "Nauru",
    },
    LanguageLookupEntry {
        canonical: "nav",
        bibliographic: "",
        two_letter: "nv",
        english_name: "Navajo; Navaho",
    },
    LanguageLookupEntry {
        canonical: "nbl",
        bibliographic: "",
        two_letter: "nr",
        english_name: "Ndebele, South; South Ndebele",
    },
    LanguageLookupEntry {
        canonical: "nde",
        bibliographic: "",
        two_letter: "nd",
        english_name: "Ndebele, North; North Ndebele",
    },
    LanguageLookupEntry {
        canonical: "ndo",
        bibliographic: "",
        two_letter: "ng",
        english_name: "Ndonga",
    },
    LanguageLookupEntry {
        canonical: "nds",
        bibliographic: "",
        two_letter: "",
        english_name: "Low German; Low Saxon; German, Low; Saxon, Low",
    },
    LanguageLookupEntry {
        canonical: "nep",
        bibliographic: "",
        two_letter: "ne",
        english_name: "Nepali",
    },
    LanguageLookupEntry {
        canonical: "new",
        bibliographic: "",
        two_letter: "",
        english_name: "Nepal Bhasa; Newari",
    },
    LanguageLookupEntry {
        canonical: "nia",
        bibliographic: "",
        two_letter: "",
        english_name: "Nias",
    },
    LanguageLookupEntry {
        canonical: "nic",
        bibliographic: "",
        two_letter: "",
        english_name: "Niger-Kordofanian languages",
    },
    LanguageLookupEntry {
        canonical: "niu",
        bibliographic: "",
        two_letter: "",
        english_name: "Niuean",
    },
    LanguageLookupEntry {
        canonical: "nld",
        bibliographic: "dut",
        two_letter: "nl",
        english_name: "Dutch; Flemish",
    },
    LanguageLookupEntry {
        canonical: "nno",
        bibliographic: "",
        two_letter: "nn",
        english_name: "Norwegian (Nynorsk)",
    },
    LanguageLookupEntry {
        canonical: "nob",
        bibliographic: "",
        two_letter: "nb",
        english_name: "Norwegian (Bokmal)",
    },
    LanguageLookupEntry {
        canonical: "nog",
        bibliographic: "",
        two_letter: "",
        english_name: "Nogai",
    },
    LanguageLookupEntry {
        canonical: "non",
        bibliographic: "",
        two_letter: "",
        english_name: "Norse, Old",
    },
    LanguageLookupEntry {
        canonical: "nor",
        bibliographic: "",
        two_letter: "no",
        english_name: "Norwegian",
    },
    LanguageLookupEntry {
        canonical: "nqo",
        bibliographic: "",
        two_letter: "",
        english_name: "N'Ko",
    },
    LanguageLookupEntry {
        canonical: "nso",
        bibliographic: "",
        two_letter: "",
        english_name: "Pedi; Sepedi; Northern Sotho",
    },
    LanguageLookupEntry {
        canonical: "nub",
        bibliographic: "",
        two_letter: "",
        english_name: "Nubian languages",
    },
    LanguageLookupEntry {
        canonical: "nwc",
        bibliographic: "",
        two_letter: "",
        english_name: "Classical Newari; Old Newari; Classical Nepal Bhasa",
    },
    LanguageLookupEntry {
        canonical: "nya",
        bibliographic: "",
        two_letter: "ny",
        english_name: "Chichewa; Chewa; Nyanja",
    },
    LanguageLookupEntry {
        canonical: "nym",
        bibliographic: "",
        two_letter: "",
        english_name: "Nyamwezi",
    },
    LanguageLookupEntry {
        canonical: "nyn",
        bibliographic: "",
        two_letter: "",
        english_name: "Nyankole",
    },
    LanguageLookupEntry {
        canonical: "nyo",
        bibliographic: "",
        two_letter: "",
        english_name: "Nyoro",
    },
    LanguageLookupEntry {
        canonical: "nzi",
        bibliographic: "",
        two_letter: "",
        english_name: "Nzima",
    },
    LanguageLookupEntry {
        canonical: "oci",
        bibliographic: "",
        two_letter: "oc",
        english_name: "Occitan (post 1500); Proven\u{00e7}al",
    },
    LanguageLookupEntry {
        canonical: "oji",
        bibliographic: "",
        two_letter: "oj",
        english_name: "Ojibwa",
    },
    LanguageLookupEntry {
        canonical: "ori",
        bibliographic: "",
        two_letter: "or",
        english_name: "Oriya",
    },
    LanguageLookupEntry {
        canonical: "orm",
        bibliographic: "",
        two_letter: "om",
        english_name: "Oromo",
    },
    LanguageLookupEntry {
        canonical: "osa",
        bibliographic: "",
        two_letter: "",
        english_name: "Osage",
    },
    LanguageLookupEntry {
        canonical: "oss",
        bibliographic: "",
        two_letter: "os",
        english_name: "Ossetian; Ossetic",
    },
    LanguageLookupEntry {
        canonical: "ota",
        bibliographic: "",
        two_letter: "",
        english_name: "Turkish, Ottoman (1500-1928)",
    },
    LanguageLookupEntry {
        canonical: "oto",
        bibliographic: "",
        two_letter: "",
        english_name: "Otomian languages",
    },
    LanguageLookupEntry {
        canonical: "paa",
        bibliographic: "",
        two_letter: "",
        english_name: "Papuan languages",
    },
    LanguageLookupEntry {
        canonical: "pag",
        bibliographic: "",
        two_letter: "",
        english_name: "Pangasinan",
    },
    LanguageLookupEntry {
        canonical: "pal",
        bibliographic: "",
        two_letter: "",
        english_name: "Pahlavi",
    },
    LanguageLookupEntry {
        canonical: "pam",
        bibliographic: "",
        two_letter: "",
        english_name: "Pampanga; Kapampangan",
    },
    LanguageLookupEntry {
        canonical: "pan",
        bibliographic: "",
        two_letter: "pa",
        english_name: "Panjabi; Punjabi",
    },
    LanguageLookupEntry {
        canonical: "pap",
        bibliographic: "",
        two_letter: "",
        english_name: "Papiamento",
    },
    LanguageLookupEntry {
        canonical: "pau",
        bibliographic: "",
        two_letter: "",
        english_name: "Palauan",
    },
    LanguageLookupEntry {
        canonical: "peo",
        bibliographic: "",
        two_letter: "",
        english_name: "Persian, Old (ca.600-400 B.C.)",
    },
    LanguageLookupEntry {
        canonical: "phi",
        bibliographic: "",
        two_letter: "",
        english_name: "Philippine languages",
    },
    LanguageLookupEntry {
        canonical: "phn",
        bibliographic: "",
        two_letter: "",
        english_name: "Phoenician",
    },
    LanguageLookupEntry {
        canonical: "pli",
        bibliographic: "",
        two_letter: "pi",
        english_name: "Pali",
    },
    LanguageLookupEntry {
        canonical: "pol",
        bibliographic: "",
        two_letter: "pl",
        english_name: "Polish",
    },
    LanguageLookupEntry {
        canonical: "pon",
        bibliographic: "",
        two_letter: "",
        english_name: "Pohnpeian",
    },
    LanguageLookupEntry {
        canonical: "por",
        bibliographic: "",
        two_letter: "pt",
        english_name: "Portuguese",
    },
    LanguageLookupEntry {
        canonical: "por",
        bibliographic: "",
        two_letter: "pt-pt",
        english_name: "Portuguese (Portugal)",
    },
    LanguageLookupEntry {
        canonical: "por",
        bibliographic: "",
        two_letter: "pt-br",
        english_name: "Portuguese (Brazil)",
    },
    LanguageLookupEntry {
        canonical: "pra",
        bibliographic: "",
        two_letter: "",
        english_name: "Prakrit languages",
    },
    LanguageLookupEntry {
        canonical: "pro",
        bibliographic: "",
        two_letter: "",
        english_name: "Proven\u{00e7}al, Old (to 1500)",
    },
    LanguageLookupEntry {
        canonical: "pus",
        bibliographic: "",
        two_letter: "ps",
        english_name: "Pushto; Pashto",
    },
    LanguageLookupEntry {
        canonical: "qaa-qtz",
        bibliographic: "",
        two_letter: "",
        english_name: "Reserved for local use",
    },
    LanguageLookupEntry {
        canonical: "que",
        bibliographic: "",
        two_letter: "qu",
        english_name: "Quechua",
    },
    LanguageLookupEntry {
        canonical: "raj",
        bibliographic: "",
        two_letter: "",
        english_name: "Rajasthani",
    },
    LanguageLookupEntry {
        canonical: "rap",
        bibliographic: "",
        two_letter: "",
        english_name: "Rapanui",
    },
    LanguageLookupEntry {
        canonical: "rar",
        bibliographic: "",
        two_letter: "",
        english_name: "Rarotongan; Cook Islands Maori",
    },
    LanguageLookupEntry {
        canonical: "roa",
        bibliographic: "",
        two_letter: "",
        english_name: "Romance languages",
    },
    LanguageLookupEntry {
        canonical: "roh",
        bibliographic: "",
        two_letter: "rm",
        english_name: "Romansh",
    },
    LanguageLookupEntry {
        canonical: "rom",
        bibliographic: "",
        two_letter: "",
        english_name: "Romany",
    },
    LanguageLookupEntry {
        canonical: "ron",
        bibliographic: "rum",
        two_letter: "ro",
        english_name: "Romanian; Moldavian; Moldovan",
    },
    LanguageLookupEntry {
        canonical: "run",
        bibliographic: "",
        two_letter: "rn",
        english_name: "Rundi",
    },
    LanguageLookupEntry {
        canonical: "rup",
        bibliographic: "",
        two_letter: "",
        english_name: "Aromanian; Arumanian; Macedo-Romanian",
    },
    LanguageLookupEntry {
        canonical: "rus",
        bibliographic: "",
        two_letter: "ru",
        english_name: "Russian",
    },
    LanguageLookupEntry {
        canonical: "sad",
        bibliographic: "",
        two_letter: "",
        english_name: "Sandawe",
    },
    LanguageLookupEntry {
        canonical: "sag",
        bibliographic: "",
        two_letter: "sg",
        english_name: "Sango",
    },
    LanguageLookupEntry {
        canonical: "sah",
        bibliographic: "",
        two_letter: "",
        english_name: "Yakut",
    },
    LanguageLookupEntry {
        canonical: "sai",
        bibliographic: "",
        two_letter: "",
        english_name: "South American Indian (Other)",
    },
    LanguageLookupEntry {
        canonical: "sal",
        bibliographic: "",
        two_letter: "",
        english_name: "Salishan languages",
    },
    LanguageLookupEntry {
        canonical: "sam",
        bibliographic: "",
        two_letter: "",
        english_name: "Samaritan Aramaic",
    },
    LanguageLookupEntry {
        canonical: "san",
        bibliographic: "",
        two_letter: "sa",
        english_name: "Sanskrit",
    },
    LanguageLookupEntry {
        canonical: "sas",
        bibliographic: "",
        two_letter: "",
        english_name: "Sasak",
    },
    LanguageLookupEntry {
        canonical: "sat",
        bibliographic: "",
        two_letter: "",
        english_name: "Santali",
    },
    LanguageLookupEntry {
        canonical: "srp",
        bibliographic: "",
        two_letter: "sr",
        english_name: "Serbian",
    },
    LanguageLookupEntry {
        canonical: "scn",
        bibliographic: "",
        two_letter: "",
        english_name: "Sicilian",
    },
    LanguageLookupEntry {
        canonical: "sco",
        bibliographic: "",
        two_letter: "",
        english_name: "Scots",
    },
    LanguageLookupEntry {
        canonical: "sel",
        bibliographic: "",
        two_letter: "",
        english_name: "Selkup",
    },
    LanguageLookupEntry {
        canonical: "sem",
        bibliographic: "",
        two_letter: "",
        english_name: "Semitic languages",
    },
    LanguageLookupEntry {
        canonical: "sga",
        bibliographic: "",
        two_letter: "",
        english_name: "Irish, Old (to 900)",
    },
    LanguageLookupEntry {
        canonical: "sgn",
        bibliographic: "",
        two_letter: "",
        english_name: "Sign Languages",
    },
    LanguageLookupEntry {
        canonical: "shn",
        bibliographic: "",
        two_letter: "",
        english_name: "Shan",
    },
    LanguageLookupEntry {
        canonical: "sid",
        bibliographic: "",
        two_letter: "",
        english_name: "Sidamo",
    },
    LanguageLookupEntry {
        canonical: "sin",
        bibliographic: "",
        two_letter: "si",
        english_name: "Sinhala; Sinhalese",
    },
    LanguageLookupEntry {
        canonical: "sio",
        bibliographic: "",
        two_letter: "",
        english_name: "Siouan languages",
    },
    LanguageLookupEntry {
        canonical: "sit",
        bibliographic: "",
        two_letter: "",
        english_name: "Sino-Tibetan languages",
    },
    LanguageLookupEntry {
        canonical: "sla",
        bibliographic: "",
        two_letter: "",
        english_name: "Slavic languages",
    },
    LanguageLookupEntry {
        canonical: "slk",
        bibliographic: "slo",
        two_letter: "sk",
        english_name: "Slovak",
    },
    LanguageLookupEntry {
        canonical: "slv",
        bibliographic: "",
        two_letter: "sl",
        english_name: "Slovenian",
    },
    LanguageLookupEntry {
        canonical: "sma",
        bibliographic: "",
        two_letter: "",
        english_name: "Southern Sami",
    },
    LanguageLookupEntry {
        canonical: "sme",
        bibliographic: "",
        two_letter: "se",
        english_name: "Northern Sami",
    },
    LanguageLookupEntry {
        canonical: "smi",
        bibliographic: "",
        two_letter: "",
        english_name: "Sami languages",
    },
    LanguageLookupEntry {
        canonical: "smj",
        bibliographic: "",
        two_letter: "",
        english_name: "Sami (Lule)",
    },
    LanguageLookupEntry {
        canonical: "smn",
        bibliographic: "",
        two_letter: "",
        english_name: "Sami (Inari)",
    },
    LanguageLookupEntry {
        canonical: "smo",
        bibliographic: "",
        two_letter: "sm",
        english_name: "Samoan",
    },
    LanguageLookupEntry {
        canonical: "sms",
        bibliographic: "",
        two_letter: "",
        english_name: "Sami (Skolt)",
    },
    LanguageLookupEntry {
        canonical: "sna",
        bibliographic: "",
        two_letter: "sn",
        english_name: "Shona",
    },
    LanguageLookupEntry {
        canonical: "snd",
        bibliographic: "",
        two_letter: "sd",
        english_name: "Sindhi",
    },
    LanguageLookupEntry {
        canonical: "snk",
        bibliographic: "",
        two_letter: "",
        english_name: "Soninke",
    },
    LanguageLookupEntry {
        canonical: "sog",
        bibliographic: "",
        two_letter: "",
        english_name: "Sogdian",
    },
    LanguageLookupEntry {
        canonical: "som",
        bibliographic: "",
        two_letter: "so",
        english_name: "Somali",
    },
    LanguageLookupEntry {
        canonical: "son",
        bibliographic: "",
        two_letter: "",
        english_name: "Songhai languages",
    },
    LanguageLookupEntry {
        canonical: "sot",
        bibliographic: "",
        two_letter: "st",
        english_name: "Sotho, Southern",
    },
    LanguageLookupEntry {
        canonical: "spa",
        bibliographic: "",
        two_letter: "es",
        english_name: "Spanish; Castilian",
    },
    LanguageLookupEntry {
        canonical: "spa",
        bibliographic: "",
        two_letter: "es-419",
        english_name: "Spanish; Latin",
    },
    LanguageLookupEntry {
        canonical: "sqi",
        bibliographic: "alb",
        two_letter: "sq",
        english_name: "Albanian",
    },
    LanguageLookupEntry {
        canonical: "srd",
        bibliographic: "",
        two_letter: "sc",
        english_name: "Sardinian",
    },
    LanguageLookupEntry {
        canonical: "srn",
        bibliographic: "",
        two_letter: "",
        english_name: "Sranan Tongo",
    },
    LanguageLookupEntry {
        canonical: "srr",
        bibliographic: "",
        two_letter: "",
        english_name: "Serer",
    },
    LanguageLookupEntry {
        canonical: "ssa",
        bibliographic: "",
        two_letter: "",
        english_name: "Nilo-Saharan languages",
    },
    LanguageLookupEntry {
        canonical: "ssw",
        bibliographic: "",
        two_letter: "ss",
        english_name: "Swati",
    },
    LanguageLookupEntry {
        canonical: "suk",
        bibliographic: "",
        two_letter: "",
        english_name: "Sukuma",
    },
    LanguageLookupEntry {
        canonical: "sun",
        bibliographic: "",
        two_letter: "su",
        english_name: "Sundanese",
    },
    LanguageLookupEntry {
        canonical: "sus",
        bibliographic: "",
        two_letter: "",
        english_name: "Susu",
    },
    LanguageLookupEntry {
        canonical: "sux",
        bibliographic: "",
        two_letter: "",
        english_name: "Sumerian",
    },
    LanguageLookupEntry {
        canonical: "swa",
        bibliographic: "",
        two_letter: "sw",
        english_name: "Swahili",
    },
    LanguageLookupEntry {
        canonical: "swe",
        bibliographic: "",
        two_letter: "sv",
        english_name: "Swedish",
    },
    LanguageLookupEntry {
        canonical: "syc",
        bibliographic: "",
        two_letter: "",
        english_name: "Classical Syriac",
    },
    LanguageLookupEntry {
        canonical: "syr",
        bibliographic: "",
        two_letter: "",
        english_name: "Syriac",
    },
    LanguageLookupEntry {
        canonical: "tah",
        bibliographic: "",
        two_letter: "ty",
        english_name: "Tahitian",
    },
    LanguageLookupEntry {
        canonical: "tai",
        bibliographic: "",
        two_letter: "",
        english_name: "Tai languages",
    },
    LanguageLookupEntry {
        canonical: "tam",
        bibliographic: "",
        two_letter: "ta",
        english_name: "Tamil",
    },
    LanguageLookupEntry {
        canonical: "tat",
        bibliographic: "",
        two_letter: "tt",
        english_name: "Tatar",
    },
    LanguageLookupEntry {
        canonical: "tel",
        bibliographic: "",
        two_letter: "te",
        english_name: "Telugu",
    },
    LanguageLookupEntry {
        canonical: "tem",
        bibliographic: "",
        two_letter: "",
        english_name: "Timne",
    },
    LanguageLookupEntry {
        canonical: "ter",
        bibliographic: "",
        two_letter: "",
        english_name: "Tereno",
    },
    LanguageLookupEntry {
        canonical: "tet",
        bibliographic: "",
        two_letter: "",
        english_name: "Tetum",
    },
    LanguageLookupEntry {
        canonical: "tgk",
        bibliographic: "",
        two_letter: "tg",
        english_name: "Tajik",
    },
    LanguageLookupEntry {
        canonical: "tgl",
        bibliographic: "",
        two_letter: "tl",
        english_name: "Tagalog",
    },
    LanguageLookupEntry {
        canonical: "tha",
        bibliographic: "",
        two_letter: "th",
        english_name: "Thai",
    },
    LanguageLookupEntry {
        canonical: "tig",
        bibliographic: "",
        two_letter: "",
        english_name: "Tigre",
    },
    LanguageLookupEntry {
        canonical: "tir",
        bibliographic: "",
        two_letter: "ti",
        english_name: "Tigrinya",
    },
    LanguageLookupEntry {
        canonical: "tiv",
        bibliographic: "",
        two_letter: "",
        english_name: "Tiv",
    },
    LanguageLookupEntry {
        canonical: "tkl",
        bibliographic: "",
        two_letter: "",
        english_name: "Tokelau",
    },
    LanguageLookupEntry {
        canonical: "tlh",
        bibliographic: "",
        two_letter: "",
        english_name: "Klingon; tlhIngan-Hol",
    },
    LanguageLookupEntry {
        canonical: "tli",
        bibliographic: "",
        two_letter: "",
        english_name: "Tlingit",
    },
    LanguageLookupEntry {
        canonical: "tmh",
        bibliographic: "",
        two_letter: "",
        english_name: "Tamashek",
    },
    LanguageLookupEntry {
        canonical: "tog",
        bibliographic: "",
        two_letter: "",
        english_name: "Tonga (Nyasa)",
    },
    LanguageLookupEntry {
        canonical: "ton",
        bibliographic: "",
        two_letter: "to",
        english_name: "Tonga (Tonga Islands)",
    },
    LanguageLookupEntry {
        canonical: "tpi",
        bibliographic: "",
        two_letter: "",
        english_name: "Tok Pisin",
    },
    LanguageLookupEntry {
        canonical: "tsi",
        bibliographic: "",
        two_letter: "",
        english_name: "Tsimshian",
    },
    LanguageLookupEntry {
        canonical: "tsn",
        bibliographic: "",
        two_letter: "tn",
        english_name: "Tswana",
    },
    LanguageLookupEntry {
        canonical: "tso",
        bibliographic: "",
        two_letter: "ts",
        english_name: "Tsonga",
    },
    LanguageLookupEntry {
        canonical: "tuk",
        bibliographic: "",
        two_letter: "tk",
        english_name: "Turkmen",
    },
    LanguageLookupEntry {
        canonical: "tum",
        bibliographic: "",
        two_letter: "",
        english_name: "Tumbuka",
    },
    LanguageLookupEntry {
        canonical: "tup",
        bibliographic: "",
        two_letter: "",
        english_name: "Tupi languages",
    },
    LanguageLookupEntry {
        canonical: "tur",
        bibliographic: "",
        two_letter: "tr",
        english_name: "Turkish",
    },
    LanguageLookupEntry {
        canonical: "tut",
        bibliographic: "",
        two_letter: "",
        english_name: "Altaic languages",
    },
    LanguageLookupEntry {
        canonical: "tvl",
        bibliographic: "",
        two_letter: "",
        english_name: "Tuvalu",
    },
    LanguageLookupEntry {
        canonical: "twi",
        bibliographic: "",
        two_letter: "tw",
        english_name: "Twi",
    },
    LanguageLookupEntry {
        canonical: "tyv",
        bibliographic: "",
        two_letter: "",
        english_name: "Tuvinian",
    },
    LanguageLookupEntry {
        canonical: "udm",
        bibliographic: "",
        two_letter: "",
        english_name: "Udmurt",
    },
    LanguageLookupEntry {
        canonical: "uga",
        bibliographic: "",
        two_letter: "",
        english_name: "Ugaritic",
    },
    LanguageLookupEntry {
        canonical: "uig",
        bibliographic: "",
        two_letter: "ug",
        english_name: "Uighur; Uyghur",
    },
    LanguageLookupEntry {
        canonical: "ukr",
        bibliographic: "",
        two_letter: "uk",
        english_name: "Ukrainian",
    },
    LanguageLookupEntry {
        canonical: "umb",
        bibliographic: "",
        two_letter: "",
        english_name: "Umbundu",
    },
    LanguageLookupEntry {
        canonical: "und",
        bibliographic: "",
        two_letter: "",
        english_name: "Undetermined",
    },
    LanguageLookupEntry {
        canonical: "urd",
        bibliographic: "",
        two_letter: "ur",
        english_name: "Urdu",
    },
    LanguageLookupEntry {
        canonical: "uzb",
        bibliographic: "",
        two_letter: "uz",
        english_name: "Uzbek",
    },
    LanguageLookupEntry {
        canonical: "vai",
        bibliographic: "",
        two_letter: "",
        english_name: "Vai",
    },
    LanguageLookupEntry {
        canonical: "ven",
        bibliographic: "",
        two_letter: "ve",
        english_name: "Venda",
    },
    LanguageLookupEntry {
        canonical: "vie",
        bibliographic: "",
        two_letter: "vi",
        english_name: "Vietnamese",
    },
    LanguageLookupEntry {
        canonical: "vol",
        bibliographic: "",
        two_letter: "vo",
        english_name: "Volap\u{00fc}k",
    },
    LanguageLookupEntry {
        canonical: "vot",
        bibliographic: "",
        two_letter: "",
        english_name: "Votic",
    },
    LanguageLookupEntry {
        canonical: "wak",
        bibliographic: "",
        two_letter: "",
        english_name: "Wakashan languages",
    },
    LanguageLookupEntry {
        canonical: "wal",
        bibliographic: "",
        two_letter: "",
        english_name: "Walamo",
    },
    LanguageLookupEntry {
        canonical: "war",
        bibliographic: "",
        two_letter: "",
        english_name: "Waray",
    },
    LanguageLookupEntry {
        canonical: "was",
        bibliographic: "",
        two_letter: "",
        english_name: "Washo",
    },
    LanguageLookupEntry {
        canonical: "wen",
        bibliographic: "",
        two_letter: "",
        english_name: "Sorbian languages",
    },
    LanguageLookupEntry {
        canonical: "wln",
        bibliographic: "",
        two_letter: "wa",
        english_name: "Walloon",
    },
    LanguageLookupEntry {
        canonical: "wol",
        bibliographic: "",
        two_letter: "wo",
        english_name: "Wolof",
    },
    LanguageLookupEntry {
        canonical: "xal",
        bibliographic: "",
        two_letter: "",
        english_name: "Kalmyk; Oirat",
    },
    LanguageLookupEntry {
        canonical: "xho",
        bibliographic: "",
        two_letter: "xh",
        english_name: "Xhosa",
    },
    LanguageLookupEntry {
        canonical: "yao",
        bibliographic: "",
        two_letter: "",
        english_name: "Yao",
    },
    LanguageLookupEntry {
        canonical: "yap",
        bibliographic: "",
        two_letter: "",
        english_name: "Yapese",
    },
    LanguageLookupEntry {
        canonical: "yid",
        bibliographic: "",
        two_letter: "yi",
        english_name: "Yiddish",
    },
    LanguageLookupEntry {
        canonical: "yor",
        bibliographic: "",
        two_letter: "yo",
        english_name: "Yoruba",
    },
    LanguageLookupEntry {
        canonical: "ypk",
        bibliographic: "",
        two_letter: "",
        english_name: "Yupik languages",
    },
    LanguageLookupEntry {
        canonical: "zap",
        bibliographic: "",
        two_letter: "",
        english_name: "Zapotec",
    },
    LanguageLookupEntry {
        canonical: "zbl",
        bibliographic: "",
        two_letter: "",
        english_name: "Blissymbols; Blissymbolics; Bliss",
    },
    LanguageLookupEntry {
        canonical: "zen",
        bibliographic: "",
        two_letter: "",
        english_name: "Zenaga",
    },
    LanguageLookupEntry {
        canonical: "zgh",
        bibliographic: "",
        two_letter: "",
        english_name: "Standard Moroccan Tamazight",
    },
    LanguageLookupEntry {
        canonical: "zha",
        bibliographic: "",
        two_letter: "za",
        english_name: "Zhuang; Chuang",
    },
    LanguageLookupEntry {
        canonical: "zho",
        bibliographic: "chi",
        two_letter: "zh",
        english_name: "Chinese",
    },
    LanguageLookupEntry {
        canonical: "zho",
        bibliographic: "chi",
        two_letter: "ze",
        english_name: "Chinese (Bilingual)",
    },
    LanguageLookupEntry {
        canonical: "zho",
        bibliographic: "chi",
        two_letter: "zh-cn",
        english_name: "Chinese (Simplified)",
    },
    LanguageLookupEntry {
        canonical: "zho",
        bibliographic: "chi",
        two_letter: "zh-hans",
        english_name: "Chinese (Simplified)",
    },
    LanguageLookupEntry {
        canonical: "zho",
        bibliographic: "chi",
        two_letter: "zh-tw",
        english_name: "Chinese (Traditional)",
    },
    LanguageLookupEntry {
        canonical: "zho",
        bibliographic: "chi",
        two_letter: "zh-hant",
        english_name: "Chinese (Traditional)",
    },
    LanguageLookupEntry {
        canonical: "zho",
        bibliographic: "chi",
        two_letter: "zh-hk",
        english_name: "Chinese (Hong Kong)",
    },
    LanguageLookupEntry {
        canonical: "znd",
        bibliographic: "",
        two_letter: "",
        english_name: "Zande languages",
    },
    LanguageLookupEntry {
        canonical: "zul",
        bibliographic: "",
        two_letter: "zu",
        english_name: "Zulu",
    },
    LanguageLookupEntry {
        canonical: "zun",
        bibliographic: "",
        two_letter: "",
        english_name: "Zuni",
    },
    LanguageLookupEntry {
        canonical: "zxx",
        bibliographic: "",
        two_letter: "",
        english_name: "No linguistic content; Not applicable",
    },
    LanguageLookupEntry {
        canonical: "zza",
        bibliographic: "",
        two_letter: "",
        english_name: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
    },
];
