use crate::scoring_weights::ScoringWeights;

/// Reputation tier for a release group.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GroupTier {
    /// Top-tier groups (e.g. TRaSH Tier 01 WEB, Tier 01 Remux)
    Gold,
    /// Great groups (e.g. TRaSH Tier 02)
    Silver,
    /// Good groups (e.g. TRaSH Tier 03)
    Bronze,
    /// Known-bad groups (LQ, bad dual audio)
    Banned,
}

/// What source context a group is known for.
/// A group might be Gold for WEB but unknown for BluRay.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SourceContext {
    Web,
    BluRay,
    UhdBluRay,
    Remux,
    Anime,
    /// Applies regardless of source (e.g. banned groups).
    Any,
}

#[derive(Debug, Clone, Copy)]
pub struct GroupEntry {
    pub name: &'static str,
    pub tier: GroupTier,
    pub source_context: SourceContext,
}

/// Look up a release group's tier, considering source context.
///
/// Strategy:
/// 1. Try exact match on (name, source_context) derived from the release
/// 2. Fall back to (name, Any) for groups that are tier-rated regardless of source
/// 3. No match → None (caller applies `group_unknown_penalty`)
pub fn lookup_group(
    name: &str,
    source: Option<&str>,
    is_remux: bool,
) -> Option<&'static GroupEntry> {
    let name_upper = name.to_ascii_uppercase();
    let ctx = source_to_context(source, is_remux);

    // Try source-specific match first
    if let Some(entry) = GROUPS
        .iter()
        .find(|g| g.name.eq_ignore_ascii_case(&name_upper) && g.source_context == ctx)
    {
        return Some(entry);
    }

    // Fall back to Any context (banned groups, etc.)
    GROUPS.iter().find(|g| {
        g.name.eq_ignore_ascii_case(&name_upper) && g.source_context == SourceContext::Any
    })
}

/// Map a parsed source string + remux flag to our SourceContext.
fn source_to_context(source: Option<&str>, is_remux: bool) -> SourceContext {
    if is_remux {
        return SourceContext::Remux;
    }
    match source {
        Some("WEB-DL") | Some("WEBRIP") => SourceContext::Web,
        Some("BLURAY") => SourceContext::BluRay,
        _ => SourceContext::Any,
    }
}

/// Apply release group scoring to a decision.
///
/// Uses the group database to look up the release group's tier for its source
/// context, then applies the corresponding weight from the persona.
pub fn apply_release_group_scoring(
    weights: &ScoringWeights,
    group: Option<&str>,
    source: Option<&str>,
    is_remux: bool,
) -> (&'static str, i32) {
    let Some(name) = group else {
        return ("group_unknown", weights.group_unknown_penalty);
    };

    if name.is_empty() {
        return ("group_unknown", weights.group_unknown_penalty);
    }

    match lookup_group(name, source, is_remux) {
        Some(entry) => match entry.tier {
            GroupTier::Gold => ("group_gold", weights.group_gold),
            GroupTier::Silver => ("group_silver", weights.group_silver),
            GroupTier::Bronze => ("group_bronze", weights.group_bronze),
            GroupTier::Banned => ("group_banned", weights.group_banned),
        },
        None => ("group_unknown", weights.group_unknown_penalty),
    }
}

// ─── Group database ──────────────────────────────────────────────────────────
//
// Sourced from TRaSH Guides (github.com/TRaSH-Guides/Guides) and community
// sources. Maintained at release time via AI-validated review — see
// scripts/prompts/validate-release-data.md.
//
// Tiers follow TRaSH scoring:
//   Tier 01 → Gold    (best quality for that source context)
//   Tier 02 → Silver  (great quality)
//   Tier 03 → Bronze  (good quality)
//   LQ/Bad  → Banned  (known problematic)

macro_rules! group {
    ($name:expr, $tier:ident, $ctx:ident) => {
        GroupEntry {
            name: $name,
            tier: GroupTier::$tier,
            source_context: SourceContext::$ctx,
        }
    };
}

static GROUPS: &[GroupEntry] = &[
    // ── WEB Tier 01 (Gold) ───────────────────────────────────────────────────
    group!("ABBIE", Gold, Web),
    group!("ABBiE", Gold, Web),
    group!("AJP69", Gold, Web),
    group!("APEX", Gold, Web),
    group!("PAXA", Gold, Web),
    group!("PEXA", Gold, Web),
    group!("XEPA", Gold, Web),
    group!("BLUTONiUM", Gold, Web),
    group!("BYNDR", Gold, Web),
    group!("CasStudio", Gold, Web),
    group!("CMRG", Gold, Web),
    group!("CRFW", Gold, Web),
    group!("CRUD", Gold, Web),
    group!("CtrlHD", Gold, Web),
    group!("FLUX", Gold, Web),
    group!("GNOME", Gold, Web),
    group!("HONE", Gold, Web),
    group!("KiNGS", Gold, Web),
    group!("Kitsune", Gold, Web),
    group!("monkee", Gold, Web),
    group!("NOSiViD", Gold, Web),
    group!("NTb", Gold, Web),
    group!("NTG", Gold, Web),
    group!("QOQ", Gold, Web),
    group!("RAWR", Gold, Web),
    group!("RTN", Gold, Web),
    group!("SiC", Gold, Web),
    group!("T6D", Gold, Web),
    group!("TEPES", Gold, Web),
    group!("TheFarm", Gold, Web),
    group!("TOMMY", Gold, Web),
    group!("ViSUM", Gold, Web),
    group!("ZoroSenpai", Gold, Web),
    // ── WEB Tier 02 (Silver) ─────────────────────────────────────────────────
    group!("3cTWeB", Silver, Web),
    group!("BTW", Silver, Web),
    group!("Chotab", Silver, Web),
    group!("Cinefeel", Silver, Web),
    group!("CiT", Silver, Web),
    group!("Coo7", Silver, Web),
    group!("dB", Silver, Web),
    group!("DEEP", Silver, Web),
    group!("END", Silver, Web),
    group!("ETHiCS", Silver, Web),
    group!("FC", Silver, Web),
    group!("Flights", Silver, Web),
    group!("iJP", Silver, Web),
    group!("iKA", Silver, Web),
    group!("iT00NZ", Silver, Web),
    group!("JETIX", Silver, Web),
    group!("KHN", Silver, Web),
    group!("KiMCHI", Silver, Web),
    group!("LAZY", Silver, Web),
    group!("MiU", Silver, Web),
    group!("MZABI", Silver, Web),
    group!("NPMS", Silver, Web),
    group!("NYH", Silver, Web),
    group!("orbitron", Silver, Web),
    group!("PHOENiX", Silver, Web),
    group!("playWEB", Silver, Web),
    group!("PSiG", Silver, Web),
    group!("ROCCaT", Silver, Web),
    group!("RTFM", Silver, Web),
    group!("SA89", Silver, Web),
    group!("SbR", Silver, Web),
    group!("SDCC", Silver, Web),
    group!("SIGMA", Silver, Web),
    group!("SMURF", Silver, Web),
    group!("SPiRiT", Silver, Web),
    group!("TVSmash", Silver, Web),
    group!("WELP", Silver, Web),
    group!("XEBEC", Silver, Web),
    group!("4KBEC", Silver, Web),
    group!("CEBEX", Silver, Web),
    // ── WEB Tier 03 (Bronze) ─────────────────────────────────────────────────
    group!("BLOOM", Bronze, Web),
    group!("Dooky", Bronze, Web),
    group!("DRACULA", Bronze, Web),
    group!("GNOMiSSiON", Bronze, Web),
    group!("HHWEB", Bronze, Web),
    group!("NINJACENTRAL", Bronze, Web),
    group!("SiGMA", Bronze, Web),
    group!("SLiGNOME", Bronze, Web),
    group!("SwAgLaNdEr", Bronze, Web),
    group!("T4H", Bronze, Web),
    group!("ViSiON", Bronze, Web),
    // ── HD BluRay Tier 01 (Gold) ─────────────────────────────────────────────
    group!("BBQ", Gold, BluRay),
    group!("BMF", Gold, BluRay),
    group!("c0kE", Gold, BluRay),
    group!("Chotab", Gold, BluRay),
    group!("CRiSC", Gold, BluRay),
    group!("CtrlHD", Gold, BluRay),
    group!("D-Z0N3", Gold, BluRay),
    group!("Dariush", Gold, BluRay),
    group!("decibeL", Gold, BluRay),
    group!("DON", Gold, BluRay),
    group!("EbP", Gold, BluRay),
    group!("EDPH", Gold, BluRay),
    group!("Geek", Gold, BluRay),
    group!("LolHD", Gold, BluRay),
    group!("NCmt", Gold, BluRay),
    group!("NTb", Gold, BluRay),
    group!("PTer", Gold, BluRay),
    group!("TayTO", Gold, BluRay),
    group!("TDD", Gold, BluRay),
    group!("TnP", Gold, BluRay),
    group!("VietHD", Gold, BluRay),
    group!("ZQ", Gold, BluRay),
    group!("ZoroSenpai", Gold, BluRay),
    // ── HD BluRay Tier 02 (Silver) ───────────────────────────────────────────
    group!("ATELiER", Silver, BluRay),
    group!("EA", Silver, BluRay),
    group!("HiDt", Silver, BluRay),
    group!("HiSD", Silver, BluRay),
    group!("iFT", Silver, BluRay),
    group!("QOQ", Silver, BluRay),
    group!("SA89", Silver, BluRay),
    group!("sbR", Silver, BluRay),
    // ── HD BluRay Tier 03 (Bronze) ───────────────────────────────────────────
    group!("BHDStudio", Bronze, BluRay),
    group!("hallowed", Bronze, BluRay),
    group!("HiFi", Bronze, BluRay),
    group!("HONE", Bronze, BluRay),
    group!("LoRD", Bronze, BluRay),
    group!("playHD", Bronze, BluRay),
    group!("SPHD", Bronze, BluRay),
    group!("W4NK3R", Bronze, BluRay),
    // ── UHD BluRay Tier 01 (Gold) ────────────────────────────────────────────
    group!("CtrlHD", Gold, UhdBluRay),
    group!("MainFrame", Gold, UhdBluRay),
    group!("DON", Gold, UhdBluRay),
    group!("W4NK3R", Gold, UhdBluRay),
    // ── UHD BluRay Tier 02 (Silver) ──────────────────────────────────────────
    group!("HQMUX", Silver, UhdBluRay),
    // ── UHD BluRay Tier 03 (Bronze) ──────────────────────────────────────────
    group!("BHDStudio", Bronze, UhdBluRay),
    group!("hallowed", Bronze, UhdBluRay),
    group!("HONE", Bronze, UhdBluRay),
    group!("PTer", Bronze, UhdBluRay),
    group!("SPHD", Bronze, UhdBluRay),
    group!("WEBDV", Bronze, UhdBluRay),
    // ── Remux Tier 01 (Gold) ─────────────────────────────────────────────────
    group!("3L", Gold, Remux),
    group!("BiZKiT", Gold, Remux),
    group!("BLURANiUM", Gold, Remux),
    group!("BMF", Gold, Remux),
    group!("CiNEPHiLES", Gold, Remux),
    group!("FraMeSToR", Gold, Remux),
    group!("PiRAMiDHEAD", Gold, Remux),
    group!("PmP", Gold, Remux),
    group!("WiLDCAT", Gold, Remux),
    group!("ZQ", Gold, Remux),
    // ── Remux Tier 02 (Silver) ───────────────────────────────────────────────
    group!("12GaugeShotgun", Silver, Remux),
    group!("ATELiER", Silver, Remux),
    group!("decibeL", Silver, Remux),
    group!("EPSiLON", Silver, Remux),
    group!("HiFi", Silver, Remux),
    group!("KRaLiMaRKo", Silver, Remux),
    group!("NCmt", Silver, Remux),
    group!("playBD", Silver, Remux),
    group!("PTer", Silver, Remux),
    group!("SiCFoI", Silver, Remux),
    group!("SURFINBIRD", Silver, Remux),
    group!("TEPES", Silver, Remux),
    group!("TRiToN", Silver, Remux),
    // ── Remux Tier 03 (Bronze) ───────────────────────────────────────────────
    group!("iFT", Bronze, Remux),
    group!("NTb", Bronze, Remux),
    group!("PTP", Bronze, Remux),
    group!("SumVision", Bronze, Remux),
    group!("TOA", Bronze, Remux),
    // ── Anime Gold — BD Tier 01-02 + WEB Tier 01 ────────────────────────────
    group!("Aergia", Gold, Anime),
    group!("Arg0", Gold, Anime),
    group!("Arid", Gold, Anime),
    group!("Baws", Gold, Anime),
    group!("DemiHuman", Gold, Anime),
    group!("FateSucks", Gold, Anime),
    group!("FLE", Gold, Anime),
    group!("Flugel", Gold, Anime),
    group!("hchcsen", Gold, Anime),
    group!("hydes", Gold, Anime),
    group!("JOHNTiTOR", Gold, Anime),
    group!("JySzE", Gold, Anime),
    group!("koala", Gold, Anime),
    group!("Kulot", Gold, Anime),
    group!("LostYears", Gold, Anime),
    group!("Lulu", Gold, Anime),
    group!("LYS1TH3A", Gold, Anime),
    group!("McBalls", Gold, Anime),
    group!("Meakes", Gold, Anime),
    group!("Moxie", Gold, Anime),
    group!("NAN0", Gold, Anime),
    group!("Orphan", Gold, Anime),
    group!("PMR", Gold, Anime),
    group!("sam", Gold, Anime),
    group!("SCY", Gold, Anime),
    group!("Setsugen", Gold, Anime),
    group!("smol", Gold, Anime),
    group!("SoM", Gold, Anime),
    group!("Vodes", Gold, Anime),
    group!("WAP", Gold, Anime),
    group!("YURI", Gold, Anime),
    group!("Z4ST1N", Gold, Anime),
    group!("ZeroBuild", Gold, Anime),
    group!("ZR", Gold, Anime),
    // ── Anime Silver — BD Tier 03-04 + WEB Tier 02-03 ───────────────────────
    group!("0x539", Silver, Anime),
    group!("ABdex", Silver, Anime),
    group!("Afro", Silver, Anime),
    group!("AnoZu", Silver, Anime),
    group!("ARC", Silver, Anime),
    group!("aRMX", Silver, Anime),
    group!("Asakura", Silver, Anime),
    group!("BBT-RMX", Silver, Anime),
    group!("BiRJU", Silver, Anime),
    group!("BKC", Silver, Anime),
    group!("cappybara", Silver, Anime),
    group!("CBT", Silver, Anime),
    group!("Chimera", Silver, Anime),
    group!("ChucksMux", Silver, Anime),
    group!("CRUCiBLE", Silver, Anime),
    group!("CUNNY", Silver, Anime),
    group!("Cunnysseur", Silver, Anime),
    group!("Cyan", Silver, Anime),
    group!("Cytox", Silver, Anime),
    group!("Dae", Silver, Anime),
    group!("derp", Silver, Anime),
    group!("DIY", Silver, Anime),
    group!("Doc", Silver, Anime),
    group!("Dooky", Silver, Anime),
    group!("EXP", Silver, Anime),
    group!("fig", Silver, Anime),
    group!("Foxtrot", Silver, Anime),
    group!("Gao", Silver, Anime),
    group!("grimf", Silver, Anime),
    group!("GSK_kun", Silver, Anime),
    group!("Half-Baked", Silver, Anime),
    group!("HatSubs", Silver, Anime),
    group!("Headpatter", Silver, Anime),
    group!("IK", Silver, Anime),
    group!("Inka-Subs", Silver, Anime),
    group!("Iznjie Biznjie", Silver, Anime),
    group!("Kaleido-subs", Silver, Anime),
    group!("Kametsu", Silver, Anime),
    group!("Kawatare", Silver, Anime),
    group!("KH", Silver, Anime),
    group!("Kitsune", Silver, Anime),
    group!("LaCroiX", Silver, Anime),
    group!("LazyRemux", Silver, Anime),
    group!("Legion", Silver, Anime),
    group!("MALD", Silver, Anime),
    group!("Mehul", Silver, Anime),
    group!("Metal", Silver, Anime),
    group!("MK", Silver, Anime),
    group!("MTBB", Silver, Anime),
    group!("Mysteria", Silver, Anime),
    group!("neko-kBaraka", Silver, Anime),
    group!("Netaro", Silver, Anime),
    group!("Noiy", Silver, Anime),
    group!("Not-Vodes", Silver, Anime),
    group!("npz", Silver, Anime),
    group!("NTRX", Silver, Anime),
    group!("Okay-Subs", Silver, Anime),
    group!("OZR", Silver, Anime),
    group!("P9", Silver, Anime),
    group!("Pizza", Silver, Anime),
    group!("pog42", Silver, Anime),
    group!("Quetzal", Silver, Anime),
    group!("RaiN", Silver, Anime),
    group!("Reza", Silver, Anime),
    group!("RMX", Silver, Anime),
    group!("RUDY", Silver, Anime),
    group!("Sekkon", Silver, Anime),
    group!("Serendipity", Silver, Anime),
    group!("sgt", Silver, Anime),
    group!("Shimatta", Silver, Anime),
    group!("Slyfox", Silver, Anime),
    group!("Smoke", Silver, Anime),
    group!("SoLCE", Silver, Anime),
    group!("Spirale", Silver, Anime),
    group!("SubsMix", Silver, Anime),
    group!("SubsPlus+", Silver, Anime),
    group!("tenshi", Silver, Anime),
    group!("uba", Silver, Anime),
    group!("UDF", Silver, Anime),
    group!("UQW", Silver, Anime),
    group!("Vanilla", Silver, Anime),
    group!("Virtuality", Silver, Anime),
    group!("VULCAN", Silver, Anime),
    // ── Anime Bronze — BD Tier 05-06 + WEB Tier 04 ──────────────────────────
    group!("ANE", Bronze, Anime),
    group!("Animorphs", Bronze, Anime),
    group!("AOmundson", Bronze, Anime),
    group!("ASC", Bronze, Anime),
    group!("B00BA", Bronze, Anime),
    group!("Beatrice", Bronze, Anime),
    group!("Bunny-Apocalypse", Bronze, Anime),
    group!("Cait-Sidhe", Bronze, Anime),
    group!("CsS", Bronze, Anime),
    group!("CTR", Bronze, Anime),
    group!("CyC", Bronze, Anime),
    group!("D4C", Bronze, Anime),
    group!("Datte13", Bronze, Anime),
    group!("deanzel", Bronze, Anime),
    group!("Drag", Bronze, Anime),
    group!("EJF", Bronze, Anime),
    group!("eldon", Bronze, Anime),
    group!("Erai-raws", Bronze, Anime),
    group!("Freehold", Bronze, Anime),
    group!("GetItTwisted", Bronze, Anime),
    group!("GHS", Bronze, Anime),
    group!("Hark0N", Bronze, Anime),
    group!("Holomux", Bronze, Anime),
    group!("iKaos", Bronze, Anime),
    group!("Judgment", Bronze, Anime),
    group!("karios", Bronze, Anime),
    group!("MC", Bronze, Anime),
    group!("mottoj", Bronze, Anime),
    group!("NH", Bronze, Anime),
    group!("NTRM", Bronze, Anime),
    group!("o7", Bronze, Anime),
    group!("Pookie", Bronze, Anime),
    group!("QM", Bronze, Anime),
    group!("RASETSU", Bronze, Anime),
    group!("Starbez", Bronze, Anime),
    group!("Thighs", Bronze, Anime),
    group!("ToonsHub", Bronze, Anime),
    group!("Tsundere", Bronze, Anime),
    group!("TTGA", Bronze, Anime),
    group!("UltraRemux", Bronze, Anime),
    group!("VARYG", Bronze, Anime),
    group!("WBDP", Bronze, Anime),
    group!("WSE", Bronze, Anime),
    group!("Yoghurt", Bronze, Anime),
    group!("Yuki", Bronze, Anime),
    group!("YURASUKA", Bronze, Anime),
    // ── Banned: LQ (Low Quality) groups ──────────────────────────────────────
    group!("24xHD", Banned, Any),
    group!("41RGB", Banned, Any),
    group!("4K4U", Banned, Any),
    group!("AOC", Banned, Any),
    group!("AROMA", Banned, Any),
    group!("aXXo", Banned, Any),
    group!("AZAZE", Banned, Any),
    group!("BARC0DE", Banned, Any),
    group!("BAUCKLEY", Banned, Any),
    group!("BdC", Banned, Any),
    group!("beAst", Banned, Any),
    group!("BRiNK", Banned, Any),
    group!("BTM", Banned, Any),
    group!("C1NEM4", Banned, Any),
    group!("C4K", Banned, Any),
    group!("CDDHD", Banned, Any),
    group!("CHAOS", Banned, Any),
    group!("CHD", Banned, Any),
    group!("CHX", Banned, Any),
    group!("CiNE", Banned, Any),
    group!("COLLECTiVE", Banned, Any),
    group!("CREATiVE24", Banned, Any),
    group!("CrEwSaDe", Banned, Any),
    group!("CTFOH", Banned, Any),
    group!("d3g", Banned, Any),
    group!("D3US", Banned, Any),
    group!("DDR", Banned, Any),
    group!("DepraveD", Banned, Any),
    group!("DNL", Banned, Any),
    group!("DRX", Banned, Any),
    group!("E", Banned, Any),
    group!("EPiC", Banned, Any),
    group!("EuReKA", Banned, Any),
    group!("EVO", Banned, Any),
    group!("FaNGDiNG0", Banned, Any),
    group!("Feranki1980", Banned, Any),
    group!("FGT", Banned, Any),
    group!("FMD", Banned, Any),
    group!("FRDS", Banned, Any),
    group!("FZHD", Banned, Any),
    group!("GalaxyRG", Banned, Any),
    group!("GHD", Banned, Any),
    group!("GHOSTS", Banned, Any),
    group!("GPTHD", Banned, Any),
    group!("HDHUB4U", Banned, Any),
    group!("HDS", Banned, Any),
    group!("HDT", Banned, Any),
    group!("HDTime", Banned, Any),
    group!("HDWinG", Banned, Any),
    group!("HiQVE", Banned, Any),
    group!("iNTENSO", Banned, Any),
    group!("iPlanet", Banned, Any),
    group!("iVy", Banned, Any),
    group!("jennaortega", Banned, Any),
    group!("jennaortegaUHD", Banned, Any),
    group!("JFF", Banned, Any),
    group!("KC", Banned, Any),
    group!("KiNGDOM", Banned, Any),
    group!("KIRA", Banned, Any),
    group!("L0SERNIGHT", Banned, Any),
    group!("LAMA", Banned, Any),
    group!("Leffe", Banned, Any),
    group!("Liber8", Banned, Any),
    group!("LiGaS", Banned, Any),
    group!("LUCY", Banned, Any),
    group!("MarkII", Banned, Any),
    group!("MeGusta", Banned, Any),
    group!("Mesc", Banned, Any),
    group!("mHD", Banned, Any),
    group!("mSD", Banned, Any),
    group!("MT", Banned, Any),
    group!("MTeam", Banned, Any),
    group!("MySiLU", Banned, Any),
    group!("NhaNc3", Banned, Any),
    group!("nHD", Banned, Any),
    group!("nikt0", Banned, Any),
    group!("NoGroup", Banned, Any),
    group!("NoGrop", Banned, Any),
    group!("nSD", Banned, Any),
    group!("OFT", Banned, Any),
    group!("Pahe", Banned, Any),
    group!("Pahe.in", Banned, Any),
    group!("Pahe.ph", Banned, Any),
    group!("PATOMiEL", Banned, Any),
    group!("PiRaTeS", Banned, Any),
    group!("PRODJi", Banned, Any),
    group!("PSA", Banned, Any),
    group!("PTNK", Banned, Any),
    group!("RARBG", Banned, Any),
    group!("RDN", Banned, Any),
    group!("Rifftrax", Banned, Any),
    group!("RU4HD", Banned, Any),
    group!("SANTi", Banned, Any),
    group!("SasukeducK", Banned, Any),
    group!("Scene", Banned, Any),
    group!("SHD", Banned, Any),
    group!("ShieldBearer", Banned, Any),
    group!("STUTTERSHIT", Banned, Any),
    group!("SUNSCREEN", Banned, Any),
    group!("TBS", Banned, Any),
    group!("TEKNO3D", Banned, Any),
    group!("TG", Banned, Any),
    group!("Tigole", Banned, Any),
    group!("TIKO", Banned, Any),
    group!("VIDEOHOLE", Banned, Any),
    group!("VISIONPLUSHDR", Banned, Any),
    group!("VISIONPLUSHDR-X", Banned, Any),
    group!("VISIONPLUSHDR1000", Banned, Any),
    group!("WAF", Banned, Any),
    group!("WiKi", Banned, Any),
    group!("worldmkv", Banned, Any),
    group!("x0r", Banned, Any),
    group!("XLF", Banned, Any),
    group!("YIFY", Banned, Any),
    group!("YTS", Banned, Any),
    group!("YTS.AG", Banned, Any),
    group!("YTS.LT", Banned, Any),
    group!("YTS.MX", Banned, Any),
    group!("Zero00", Banned, Any),
    group!("Zeus", Banned, Any),
    // ── Banned: Bad dual audio groups ─────────────────────────────────────────
    group!("alfaHD", Banned, Any),
    group!("BAT", Banned, Any),
    group!("BiOMA", Banned, Any),
    group!("BlackBit", Banned, Any),
    group!("BNd", Banned, Any),
    group!("C.A.A", Banned, Any),
    group!("Cory", Banned, Any),
    group!("EXTREME", Banned, Any),
    group!("FF", Banned, Any),
    group!("FOXX", Banned, Any),
    group!("G4RiS", Banned, Any),
    group!("GUEIRA", Banned, Any),
    group!("LCD", Banned, Any),
    group!("MGE", Banned, Any),
    group!("N3G4N", Banned, Any),
    group!("ONLYMOViE", Banned, Any),
    group!("PD", Banned, Any),
    group!("PTHome", Banned, Any),
    group!("RiPER", Banned, Any),
    group!("RK", Banned, Any),
    group!("SiGLA", Banned, Any),
    group!("Tars", Banned, Any),
    group!("TM", Banned, Any),
    group!("tokar86a", Banned, Any),
    group!("TURG", Banned, Any),
    group!("TvR", Banned, Any),
    group!("vnlls", Banned, Any),
    group!("WTV", Banned, Any),
    group!("Yatogam1", Banned, Any),
    group!("YusukeFLA", Banned, Any),
    group!("ZigZag", Banned, Any),
    group!("ZNM", Banned, Any),
    // ── Banned: Anime LQ groups ──────────────────────────────────────────────
    group!("$tore-Chill", Banned, Anime),
    group!("0neshot", Banned, Anime),
    group!("224", Banned, Anime),
    group!("A-Destiny", Banned, Anime),
    group!("AceAres", Banned, Anime),
    group!("AhmadDev", Banned, Anime),
    group!("Anime Chap", Banned, Anime),
    group!("Anime Land", Banned, Anime),
    group!("Anime Time", Banned, Anime),
    group!("AnimeDynastyEN", Banned, Anime),
    group!("AnimeKuro", Banned, Anime),
    group!("AnimeRG", Banned, Anime),
    group!("Animesubs", Banned, Anime),
    group!("AnimeTR", Banned, Anime),
    group!("Anitsu", Banned, Anime),
    group!("AniVoid", Banned, Anime),
    group!("ArataEnc", Banned, Anime),
    group!("AREY", Banned, Anime),
    group!("Ari", Banned, Anime),
    group!("ASW", Banned, Anime),
    group!("BakedFish", Banned, Anime),
    group!("BDMV", Banned, Anime),
    group!("BDVD", Banned, Anime),
    group!("BJX", Banned, Anime),
    group!("BlackLuster", Banned, Anime),
    group!("bonkai77", Banned, Anime),
    group!("CameEsp", Banned, Anime),
    group!("Cat66", Banned, Anime),
    group!("CBB", Banned, Anime),
    group!("Cerberus", Banned, Anime),
    group!("Cleo", Banned, Anime),
    group!("CuaP", Banned, Anime),
    group!("DaddySubs", Banned, Anime),
    group!("DARKFLiX", Banned, Anime),
    group!("DB", Banned, Anime),
    group!("DBArabic", Banned, Anime),
    group!("Deadmau RAWS", Banned, Anime),
    group!("DeadFish", Banned, Anime),
    group!("DKB", Banned, Anime),
    group!("DP", Banned, Anime),
    group!("DsunS", Banned, Anime),
    group!("Emmid", Banned, Anime),
    group!("ExREN", Banned, Anime),
    group!("FAV", Banned, Anime),
    group!("FunArts", Banned, Anime),
    group!("GERMini", Banned, Anime),
    group!("Hakata Ramen", Banned, Anime),
    group!("Hall_of_C", Banned, Anime),
    group!("Hatsuyuki", Banned, Anime),
    group!("HAV1T", Banned, Anime),
    group!("HENiL", Banned, Anime),
    group!("Hitoku", Banned, Anime),
    group!("HollowRoxas", Banned, Anime),
    group!("HR", Banned, Anime),
    group!("ICEBLUE", Banned, Anime),
    group!("iPUNISHER", Banned, Anime),
    group!("JacobSwaggedUp", Banned, Anime),
    group!("Johnny-englishsubs", Banned, Anime),
    group!("Kallango", Banned, Anime),
    group!("Kanjouteki", Banned, Anime),
    group!("KEKMASTERS", Banned, Anime),
    group!("Kirion", Banned, Anime),
    group!("KQRM", Banned, Anime),
    group!("KRP", Banned, Anime),
    group!("LoliHouse", Banned, Anime),
    group!("M@nI", Banned, Anime),
    group!("M2TS", Banned, Anime),
    group!("mal lu zen", Banned, Anime),
    group!("Man.K", Banned, Anime),
    group!("Maximus", Banned, Anime),
    group!("MD", Banned, Anime),
    group!("mdcx", Banned, Anime),
    group!("Metaljerk", Banned, Anime),
    group!("MGD", Banned, Anime),
    group!("MiniFreeza", Banned, Anime),
    group!("MiniMTBB", Banned, Anime),
    group!("MinisCuba", Banned, Anime),
    group!("MiniTheatre", Banned, Anime),
    group!("Mites", Banned, Anime),
    group!("Modders Bay", Banned, Anime),
    group!("Mr.Deadpool", Banned, Anime),
    group!("NemDiggers", Banned, Anime),
    group!("neoHEVC", Banned, Anime),
    group!("Nokou", Banned, Anime),
    group!("NoobSubs", Banned, Anime),
    group!("NS", Banned, Anime),
    group!("Nyanpasu", Banned, Anime),
    group!("OldCastle", Banned, Anime),
    group!("Pantsu", Banned, Anime),
    group!("Pao", Banned, Anime),
    group!("phazer11", Banned, Anime),
    group!("Pixel", Banned, Anime),
    group!("Plex Friendly", Banned, Anime),
    group!("PnPSubs", Banned, Anime),
    group!("Polarwindz", Banned, Anime),
    group!("Project-gxs", Banned, Anime),
    group!("PuyaSubs", Banned, Anime),
    group!("QAS", Banned, Anime),
    group!("QCE", Banned, Anime),
    group!("Rando235", Banned, Anime),
    group!("Ranger", Banned, Anime),
    group!("Rapta", Banned, Anime),
    group!("Raze", Banned, Anime),
    group!("Reaktor", Banned, Anime),
    group!("RightShiftBy2", Banned, Anime),
    group!("Rip Time", Banned, Anime),
    group!("SAD", Banned, Anime),
    group!("Salieri", Banned, Anime),
    group!("Samir755", Banned, Anime),
    group!("SanKyuu", Banned, Anime),
    group!("SEiN", Banned, Anime),
    group!("sekkusu&ok", Banned, Anime),
    group!("SHFS", Banned, Anime),
    group!("shincaps", Banned, Anime),
    group!("SLAX", Banned, Anime),
    group!("Sokudo", Banned, Anime),
    group!("SpaceFish", Banned, Anime),
    group!("SRW", Banned, Anime),
    group!("SSA", Banned, Anime),
    group!("StrayGods", Banned, Anime),
    group!("Suki Desu", Banned, Anime),
    group!("TeamTurquoize", Banned, Anime),
    group!("Tenrai Sensei", Banned, Anime),
    group!("TnF", Banned, Anime),
    group!("TOPKEK", Banned, Anime),
    group!("Trix", Banned, Anime),
    group!("U3-Web", Banned, Anime),
    group!("UNBIASED", Banned, Anime),
    group!("uP", Banned, Anime),
    group!("USD", Banned, Anime),
    group!("Valenciano", Banned, Anime),
    group!("VipapkStudios", Banned, Anime),
    group!("Wardevil", Banned, Anime),
    group!("WtF Anime", Banned, Anime),
    group!("xiao-av1", Banned, Anime),
    group!("Yabai_Desu_NeRandomRemux", Banned, Anime),
    group!("YakuboEncodes", Banned, Anime),
    group!("youshikibi", Banned, Anime),
    group!("YuiSubs", Banned, Anime),
    group!("Yun", Banned, Anime),
    group!("zza", Banned, Anime),
];

#[cfg(test)]
#[path = "release_group_db_tests.rs"]
mod release_group_db_tests;
