[package]
name = "scryer-interface"
version = "0.19.5"
edition.workspace = true

[dependencies]
scryer-application = { path = "../scryer-application" }
scryer-domain = { path = "../scryer-domain" }
scryer-interface-acquisition = { path = "../scryer-interface-acquisition" }
scryer-interface-core = { path = "../scryer-interface-core" }
scryer-interface-import = { path = "../scryer-interface-import" }
scryer-interface-media = { path = "../scryer-interface-media" }
scryer-interface-metadata = { path = "../scryer-interface-metadata" }
scryer-interface-query = { path = "../scryer-interface-query" }
scryer-interface-security = { path = "../scryer-interface-security" }
scryer-interface-settings = { path = "../scryer-interface-settings" }
scryer-interface-subscription = { path = "../scryer-interface-subscription" }
scryer-interface-system = { path = "../scryer-interface-system" }
async-graphql = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
wiremock = { workspace = true }
