// Parser recognition snapshot from TRaSH Guides.
// Scoring and recommendation tables live in the community Rego pack.

#[allow(dead_code)]
pub const TRASH_GUIDES_SOURCE_REVISION: &str = "31a2716d03a3f554a5a2a6bd76456109d900af05";

pub static SERVICE_ALIAS_RULES: &[ServiceAliasRule] = &[
    ServiceAliasRule {
        token: "4OD",
        service: "Channel 4",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "ABEMA",
        service: "ABEMA",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "ABEMATV",
        service: "ABEMA",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "ADN",
        service: "ADN",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "ALL4",
        service: "Channel 4",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "AMAZON",
        service: "Amazon",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "AMAZONHD",
        service: "Amazon",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "AMZN",
        service: "Amazon",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "APPLE",
        service: "Apple TV+",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "APTV",
        service: "Apple TV+",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "ATV",
        service: "ATV",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "ATVP",
        service: "Apple TV+",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "AUBC",
        service: "ABC iview",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "BCORE",
        service: "BCORE",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "BGLOBAL",
        service: "B-Global",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "BILI",
        service: "Bilibili",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "BILIBILI",
        service: "Bilibili",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "CBC",
        service: "CBC Gem",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "CNLP",
        service: "CANAL+",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "CPNG",
        service: "Coupang Play",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "CR",
        service: "Crunchyroll",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "CRAV",
        service: "Crave",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "CRAVE",
        service: "Crave",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "CROLL",
        service: "Crunchyroll",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "CRUNCHY",
        service: "Crunchyroll",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "CRUNCHYR",
        service: "Crunchyroll",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "CRUNCHYROLL",
        service: "Crunchyroll",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "DCU",
        service: "DC Universe",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "DISNEY",
        service: "Disney+",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "DMM",
        service: "DMM TV",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "DSCP",
        service: "Discovery+",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "DSCV",
        service: "Discovery+",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "DSNP",
        service: "Disney+",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "DSNPHS",
        service: "Disney+ Hotstar",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "DSNY",
        service: "Disney+",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "FOD",
        service: "FOD",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "FRIDAY",
        service: "friDay Video",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "FUNI",
        service: "Funimation",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "FUNIMATION",
        service: "Funimation",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HAMI",
        service: "Hami Video",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HAMIVIDEO",
        service: "Hami Video",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HBO",
        service: "HBO Max",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HBOM",
        service: "HBO Max",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HBOMAX",
        service: "HBO Max",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HIDI",
        service: "HIDIVE",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HIDIVE",
        service: "HIDIVE",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HMAX",
        service: "HBO Max",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HTSR",
        service: "Disney+ Hotstar",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "HULU",
        service: "Hulu",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "IP",
        service: "BBC iPlayer",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "IPLAYER",
        service: "BBC iPlayer",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "IQIY",
        service: "iQIYI",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "IQIYI",
        service: "iQIYI",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "IT",
        service: "iTunes",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "ITV",
        service: "ITVX",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "ITVX",
        service: "ITVX",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "KCW",
        service: "KOCOWA",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "KKTV",
        service: "KKTV",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "KOCOWA",
        service: "KOCOWA",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "LINETV",
        service: "LINE TV",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "MAX",
        service: "HBO Max",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "MY5",
        service: "My5",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "MYTVSUPER",
        service: "myTV SUPER",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "NETFLIX",
        service: "Netflix",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "NETFLIXHD",
        service: "Netflix",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "NETFLIXUHD",
        service: "Netflix",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "NF",
        service: "Netflix",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "NLZ",
        service: "NLZiet",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "NLZIET",
        service: "NLZiet",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "NOW",
        service: "NOW",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "OVID",
        service: "OVID.tv",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "PARAMOUNT",
        service: "Paramount+",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "PATHE",
        service: "Pathé Thuis",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "PCOK",
        service: "Peacock",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "PEACOCK",
        service: "Peacock",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "PLAY",
        service: "PLAY",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "PMTP",
        service: "Paramount+",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "QIBI",
        service: "Quibi",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "QUIBI",
        service: "Quibi",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "RED",
        service: "YouTube Premium",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "ROKU",
        service: "The Roku Channel",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "SALTO",
        service: "Salto",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "SHO",
        service: "Showtime",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "SHOWTIME",
        service: "Showtime",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "STAN",
        service: "Stan",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "STRP",
        service: "Star+",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "SYFY",
        service: "SYFY",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "TVER",
        service: "TVer",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "TVING",
        service: "TVING",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "VDL",
        service: "Videoland",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "VIDEOLAND",
        service: "Videoland",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "VIKI",
        service: "Viki",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "VIU",
        service: "Viu",
        requires_web_adjacency: true,
    },
    ServiceAliasRule {
        token: "VRV",
        service: "VRV",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "WAKA",
        service: "Wakanim",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "WAKANIM",
        service: "Wakanim",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "WAVVE",
        service: "Wavve",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "WETV",
        service: "WeTV",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "WKN",
        service: "Wakanim",
        requires_web_adjacency: false,
    },
    ServiceAliasRule {
        token: "YOUKU",
        service: "Youku",
        requires_web_adjacency: false,
    },
];

pub static TOKEN_SIGNAL_RULES: &[TokenSignalRule] = &[
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &[
                "12", "D3", "AI", "ENHANCED", "UPS", "UHD", "UPSCALED", "UHD", "UPREZ",
            ],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "Upscaled",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["AIUS"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "AIUS",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["AIUS"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "AIUS",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &[
                "D34P", "AI", "ENHANCED", "UPS", "UHD", "UPSCALED", "UHD", "UPREZ",
            ],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "Upscaled",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["GUYZO"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "GuyZo",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REGRADE"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "Regrade",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REGRADE"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "Regrade",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REGRADED"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "Regrade",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REGRADED"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "Regrade",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["RW"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "RW",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["RW"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "RW",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["THE", "UPSCALER"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "TheUpscaler",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["THE", "UPSCALER"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "TheUpscaler",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["THEUPSCALER"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "TheUpscaler",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["THEUPSCALER"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "TheUpscaler",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["UPREZ"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "Upscaled",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["UPREZ"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "Upscaled",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["UPSCALED"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "Upscaled",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["UPSCALED"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "Upscaled",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["UPSCALEREGRADE"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "Regrade",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["UPSCALEREGRADE"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "Regrade",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["UPSCALEREGRADED"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "Regrade",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["UPSCALEREGRADED"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "Regrade",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["12D3", "HEVC", "AI"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "AI Upscales",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["AI", "ENHANCED"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "upscaled",
        trash_id: "bfd8eb01832d646a0a89c4deb46f8564",
        cf_name: "Upscaled",
        spec_name: "AI Upscales",
        source_path: "docs/json/radarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["AI", "ENHANCED"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "AI Upscales",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::AiEnhanced,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["D34P", "HEVC", "AI"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "upscaled",
        trash_id: "23297a736ca77c0fc8e70f8edd7ee56c",
        cf_name: "Upscaled",
        spec_name: "AI Upscales",
        source_path: "docs/json/sonarr/cf/upscaled.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["PROPER"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "repack-proper",
        trash_id: "e7718d7a3ce595f289bfee26adc178f5",
        cf_name: "Repack/Proper",
        spec_name: "Repack/Proper/Rerip",
        source_path: "docs/json/radarr/cf/repack-proper.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["PROPER"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "repack-proper",
        trash_id: "ec8fa7296b64e8cd390a1600981f3923",
        cf_name: "Repack/Proper",
        spec_name: "Repack/Proper/Rerip",
        source_path: "docs/json/sonarr/cf/repack-proper.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["PROPER2"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "repack2",
        trash_id: "ae43b294509409a6a13919dedd4764c4",
        cf_name: "Repack2",
        spec_name: "Repack/Proper 2 or REAL.PROPER/REPACK",
        source_path: "docs/json/radarr/cf/repack2.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["PROPER2"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "repack2",
        trash_id: "eb3d5cc0a2be0db205fb823640db6a3c",
        cf_name: "Repack2",
        spec_name: "Repack/Proper 2 or REAL.PROPER/REPACK",
        source_path: "docs/json/sonarr/cf/repack2.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["PROPER3"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "repack3",
        trash_id: "5caaaa1c08c1742aa4342d8c4cc463f2",
        cf_name: "Repack3",
        spec_name: "Repack/Proper 3 or REAL.REAL.PROPER/REPACK",
        source_path: "docs/json/radarr/cf/repack3.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["PROPER3"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "repack3",
        trash_id: "44e7c4de10ae50265753082e5dc76047",
        cf_name: "Repack3",
        spec_name: "Repack/Proper 3 or REAL.REAL.PROPER/REPACK",
        source_path: "docs/json/sonarr/cf/repack3.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REPACK2"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "repack2",
        trash_id: "ae43b294509409a6a13919dedd4764c4",
        cf_name: "Repack2",
        spec_name: "Repack/Proper 2 or REAL.PROPER/REPACK",
        source_path: "docs/json/radarr/cf/repack2.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REPACK2"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "repack2",
        trash_id: "eb3d5cc0a2be0db205fb823640db6a3c",
        cf_name: "Repack2",
        spec_name: "Repack/Proper 2 or REAL.PROPER/REPACK",
        source_path: "docs/json/sonarr/cf/repack2.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REPACK3"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "repack3",
        trash_id: "5caaaa1c08c1742aa4342d8c4cc463f2",
        cf_name: "Repack3",
        spec_name: "Repack/Proper 3 or REAL.REAL.PROPER/REPACK",
        source_path: "docs/json/radarr/cf/repack3.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REPACK3"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "repack3",
        trash_id: "44e7c4de10ae50265753082e5dc76047",
        cf_name: "Repack3",
        spec_name: "Repack/Proper 3 or REAL.REAL.PROPER/REPACK",
        source_path: "docs/json/sonarr/cf/repack3.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["REAL", "PROPER"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "repack2",
        trash_id: "ae43b294509409a6a13919dedd4764c4",
        cf_name: "Repack2",
        spec_name: "Repack/Proper 2 or REAL.PROPER/REPACK",
        source_path: "docs/json/radarr/cf/repack2.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Proper,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["REAL", "PROPER"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "repack2",
        trash_id: "eb3d5cc0a2be0db205fb823640db6a3c",
        cf_name: "Repack2",
        spec_name: "Repack/Proper 2 or REAL.PROPER/REPACK",
        source_path: "docs/json/sonarr/cf/repack2.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Repack,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REPACK"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "repack-proper",
        trash_id: "e7718d7a3ce595f289bfee26adc178f5",
        cf_name: "Repack/Proper",
        spec_name: "Repack/Proper/Rerip",
        source_path: "docs/json/radarr/cf/repack-proper.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Repack,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["REPACK"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "repack-proper",
        trash_id: "ec8fa7296b64e8cd390a1600981f3923",
        cf_name: "Repack/Proper",
        spec_name: "Repack/Proper/Rerip",
        source_path: "docs/json/sonarr/cf/repack-proper.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Repack,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["RERIP"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "repack-proper",
        trash_id: "e7718d7a3ce595f289bfee26adc178f5",
        cf_name: "Repack/Proper",
        spec_name: "Repack/Proper/Rerip",
        source_path: "docs/json/radarr/cf/repack-proper.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Repack,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["RERIP"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "repack-proper",
        trash_id: "ec8fa7296b64e8cd390a1600981f3923",
        cf_name: "Repack/Proper",
        spec_name: "Repack/Proper/Rerip",
        source_path: "docs/json/sonarr/cf/repack-proper.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Repack,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["REAL", "REPACK"],
        },
        facet: RuleFacet::Movie,
        app: "radarr",
        stem: "repack2",
        trash_id: "ae43b294509409a6a13919dedd4764c4",
        cf_name: "Repack2",
        spec_name: "Repack/Proper 2 or REAL.PROPER/REPACK",
        source_path: "docs/json/radarr/cf/repack2.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::Repack,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["REAL", "REPACK"],
        },
        facet: RuleFacet::Series,
        app: "sonarr",
        stem: "repack2",
        trash_id: "eb3d5cc0a2be0db205fb823640db6a3c",
        cf_name: "Repack2",
        spec_name: "Repack/Proper 2 or REAL.PROPER/REPACK",
        source_path: "docs/json/sonarr/cf/repack2.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::DubsOnly,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["DUB"],
        },
        facet: RuleFacet::Anime,
        app: "radarr",
        stem: "dubs-only",
        trash_id: "b23eae459cc960816f2d6ba84af45055",
        cf_name: "Dubs Only",
        spec_name: "Dubbed",
        source_path: "docs/json/radarr/cf/dubs-only.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::DubsOnly,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["DUB"],
        },
        facet: RuleFacet::Anime,
        app: "sonarr",
        stem: "dubs-only",
        trash_id: "9c14d194486c4014d422adc64092d794",
        cf_name: "Dubs Only",
        spec_name: "Dubbed",
        source_path: "docs/json/sonarr/cf/dubs-only.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::DubsOnly,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["DUBBED"],
        },
        facet: RuleFacet::Anime,
        app: "radarr",
        stem: "dubs-only",
        trash_id: "b23eae459cc960816f2d6ba84af45055",
        cf_name: "Dubs Only",
        spec_name: "Dubbed",
        source_path: "docs/json/radarr/cf/dubs-only.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::DubsOnly,
        pattern: TokenPattern {
            kind: TokenPatternKind::Sequence,
            tokens: &["DUBBED"],
        },
        facet: RuleFacet::Anime,
        app: "sonarr",
        stem: "dubs-only",
        trash_id: "9c14d194486c4014d422adc64092d794",
        cf_name: "Dubs Only",
        spec_name: "Dubbed",
        source_path: "docs/json/sonarr/cf/dubs-only.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::DubsOnly,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["ENG", "DUB"],
        },
        facet: RuleFacet::Anime,
        app: "radarr",
        stem: "dubs-only",
        trash_id: "b23eae459cc960816f2d6ba84af45055",
        cf_name: "Dubs Only",
        spec_name: "Dubbed",
        source_path: "docs/json/radarr/cf/dubs-only.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::DubsOnly,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["ENG", "DUB"],
        },
        facet: RuleFacet::Anime,
        app: "sonarr",
        stem: "dubs-only",
        trash_id: "9c14d194486c4014d422adc64092d794",
        cf_name: "Dubs Only",
        spec_name: "Dubbed",
        source_path: "docs/json/sonarr/cf/dubs-only.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::DubsOnly,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["FUNI", "DUB"],
        },
        facet: RuleFacet::Anime,
        app: "radarr",
        stem: "dubs-only",
        trash_id: "b23eae459cc960816f2d6ba84af45055",
        cf_name: "Dubs Only",
        spec_name: "Dubbed",
        source_path: "docs/json/radarr/cf/dubs-only.json",
    },
    TokenSignalRule {
        kind: ParserSignalKind::DubsOnly,
        pattern: TokenPattern {
            kind: TokenPatternKind::RequiredTokens,
            tokens: &["FUNI", "DUB"],
        },
        facet: RuleFacet::Anime,
        app: "sonarr",
        stem: "dubs-only",
        trash_id: "9c14d194486c4014d422adc64092d794",
        cf_name: "Dubs Only",
        spec_name: "Dubbed",
        source_path: "docs/json/sonarr/cf/dubs-only.json",
    },
];
