use scryer_infrastructure::encryption::EncryptionKey;
use std::io::{self, BufRead, Write};
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

pub fn run_init(args: Vec<String>) {
    let output_path = parse_output_arg(&args);
    let write_to_stdout = output_path.as_deref() == Some("-");

    if !write_to_stdout {
        let compose_path = output_path.as_deref().unwrap_or("docker-compose.yml");
        if Path::new(compose_path).exists() {
            eprintln!("error: {compose_path} already exists (refusing to overwrite)");
            std::process::exit(1);
        }
        if Path::new(".env").exists() {
            eprintln!("error: .env already exists (refusing to overwrite)");
            std::process::exit(1);
        }
    }

    let stdin = io::stdin();
    let mut reader = stdin.lock();

    let movies_path = prompt(
        &mut reader,
        "Movies directory on this host",
        "/media/movies",
    );
    let series_path = prompt(
        &mut reader,
        "Series directory on this host",
        "/media/series",
    );
    let encryption_key = EncryptionKey::generate().to_base64();

    let compose = generate_compose(&movies_path, &series_path);
    let env_file = generate_env(&encryption_key);

    if write_to_stdout {
        print!("{env_file}---\n{compose}");
    } else {
        let compose_path = output_path.as_deref().unwrap_or("docker-compose.yml");
        std::fs::write(compose_path, &compose).unwrap_or_else(|e| {
            eprintln!("error: failed to write {compose_path}: {e}");
            std::process::exit(1);
        });
        std::fs::write(".env", &env_file).unwrap_or_else(|e| {
            eprintln!("error: failed to write .env: {e}");
            std::process::exit(1);
        });
        std::fs::set_permissions(".env", std::fs::Permissions::from_mode(0o600)).unwrap_or_else(
            |e| {
                eprintln!("warning: could not set .env permissions to 600: {e}");
            },
        );
        eprintln!("wrote {compose_path}");
        eprintln!("wrote .env");
        eprintln!();
        eprintln!("next steps:");
        eprintln!("  docker compose up -d");
    }
}

fn parse_output_arg(args: &[String]) -> Option<String> {
    let mut iter = args.iter().skip(1); // skip binary name
    while let Some(arg) = iter.next() {
        if arg == "--output" || arg == "-o" {
            return iter.next().cloned();
        }
        if let Some(val) = arg.strip_prefix("--output=") {
            return Some(val.to_string());
        }
        // skip "init" itself
    }
    None
}

fn prompt(reader: &mut impl BufRead, label: &str, default: &str) -> String {
    eprint!("{label} [{default}]: ");
    io::stderr().flush().ok();

    let mut input = String::new();
    if reader.read_line(&mut input).is_err() {
        return default.to_string();
    }

    let trimmed = input.trim();
    if trimmed.is_empty() {
        default.to_string()
    } else {
        trimmed.to_string()
    }
}

fn generate_env(encryption_key: &str) -> String {
    format!(
        r#"# Generated by `scryer init` — do not share or commit this file.

# Encrypts passwords and API keys stored in the database.
# Do not lose this key — you will need to reconfigure secrets if it changes.
SCRYER_ENCRYPTION_KEY={encryption_key}
"#
    )
}

fn generate_compose(movies_path: &str, series_path: &str) -> String {
    // Use doubled braces for Rust format!(), which produce literal braces in output,
    // so ${{SCRYER_ENCRYPTION_KEY}} becomes ${SCRYER_ENCRYPTION_KEY} in the file.
    format!(
        r#"services:
  scryer:
    image: ghcr.io/scryer-media/scryer:latest
    container_name: scryer
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - scryer-data:/data
      - {movies_path}:/media/movies
      - {series_path}:/media/series
    environment:
      # ── Authentication ────────────────────────────────────────────
      # Beta default: authentication is disabled and all requests act
      # as the built-in admin user. Set this to "true" to require login.
      SCRYER_AUTH_ENABLED: "false"

      # ── Encryption key (from .env) ──────────────────────────────
      SCRYER_ENCRYPTION_KEY: ${{SCRYER_ENCRYPTION_KEY}}

      # ── Media paths (must match your volume mounts above) ─────────
      SCRYER_MOVIES_PATH: /media/movies
      SCRYER_SERIES_PATH: /media/series

      # ── Metadata gateway ──────────────────────────────────────────
      SCRYER_METADATA_GATEWAY_GRAPHQL_URL: https://smg.scryer.media/graphql

    # ── Upgrade procedure ───────────────────────────────────────────
    # 1. docker compose pull
    # 2. docker compose up -d
    #
    # Migrations run automatically. The scryer-data volume preserves
    # your database and all settings across upgrades.

volumes:
  scryer-data:
"#
    )
}
