[package]
name = "scryer-interface-system"
version = "0.19.12"
edition.workspace = true

[dependencies]
scryer-application = { path = "../scryer-application" }
scryer-domain = { path = "../scryer-domain" }
scryer-interface-core = { path = "../scryer-interface-core" }
scryer-interface-media = { path = "../scryer-interface-media" }
async-graphql = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
