[package]
name = "scryer-interface-media"
version = "0.19.10"
edition.workspace = true

[dependencies]
async-graphql = { workspace = true }
chrono = { workspace = true }
scryer-application = { path = "../scryer-application" }
scryer-domain = { path = "../scryer-domain" }
scryer-interface-core = { path = "../scryer-interface-core" }
scryer-interface-media-types = { path = "../scryer-interface-media-types" }
scryer-rules = { path = "../scryer-rules" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
