[package]
name = "scryer-interface-metadata"
version = "0.19.1"
edition.workspace = true

[dependencies]
async-graphql = { workspace = true }
scryer-application = { path = "../scryer-application" }
scryer-domain = { path = "../scryer-domain" }
scryer-interface-core = { path = "../scryer-interface-core" }
scryer-interface-media = { path = "../scryer-interface-media" }
