[package]
name = "scryer-webauthn"
version = "0.20.0"
edition.workspace = true

[dependencies]
aws-lc-rs = { workspace = true }
base64 = { workspace = true }
ciborium = "0.2"
coset = "0.4"
passkey-types = { version = "0.5", default-features = false, features = ["serialize_bytes_as_base64_string"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = "2"
uuid = { workspace = true }
