[package]
name = "scryer-infrastructure-notifications"
version = "0.19.8"
edition.workspace = true
publish = false

[dependencies]
scryer-domain = { path = "../scryer-domain" }
scryer-application = { path = "../scryer-application" }
scryer-infrastructure-sql = { path = "../scryer-infrastructure-sql" }
scryer-infrastructure-crypto = { path = "../scryer-infrastructure-crypto" }
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
